//! RFC-052 Phase A: oil mega-cells — the engine's own layout for a
//! fluid subgraph, used UNCROPPED as one composable unit.
//!
//! `extract_cell`'s segment crop is fatal for fluid complexes (it
//! sheds the inter-row fluid trunks — RFC-052 decision log), so a
//! mega-cell keeps the whole engine layout and attaches through its
//! own boundary records. Those records are already in the calibrated
//! orientation (north-edge south-flowing feeds, south-edge drains);
//! the one kit violation is FEED PITCH — the engine packs trunk heads
//! adjacent, the sim kit needs >=4 tiles between rigs (#363). The
//! adapter here re-pitches: translate the layout down a margin band,
//! give every boundary input a 4-pitch head at y=0, and route each
//! head through its OWN lane of the band into the original trunk head
//! (belts: column + lane-preserving corners; fluids: pipe runs, which
//! join by adjacency). Fluids never leave the mega-cell except at
//! these boundary records (RFC-052 design).

use rustc_hash::FxHashSet;

use crate::common::QualityTier;
use crate::models::{BoundaryRecord, EntityDirection, LayoutResult, PlacedEntity};
use crate::recipe_db::MachinePalette;
use crate::solver;

/// Sim-kit rig pitch (#363): adjacent feed rigs collide below 4.
const FEED_PITCH: i32 = 4;

/// Generate the engine layout for a fluid-subgraph target and adapt it
/// to the calibrated boundary form. Returns the sub-solve and the
/// adapted layout. Refuses (Err) on shapes the v1 adapter cannot route
/// without crossings — a loud refusal, never a silent overlap.
pub fn compose_mega_calibrated(
    item: &str,
    rate: f64,
    inputs: &[&str],
) -> Result<(crate::models::SolverResult, LayoutResult), String> {
    let inputs_set: FxHashSet<String> = inputs.iter().map(|s| s.to_string()).collect();
    let sr = solver::solve_with_palette_exclusions_and_quality(
        item,
        rate,
        &inputs_set,
        &MachinePalette::default(),
        "assembling-machine-3",
        &FxHashSet::default(),
        QualityTier::Normal,
    )
    .map_err(|e| format!("mega: solve {item}: {e}"))?;
    let opts = crate::bus::layout::LayoutOptions {
        // Cells are generated by the bus pipeline by definition (same
        // recursion guard as extract::generate_cell_layout).
        cell_composition: super::CellComposition::Off,
        ..Default::default()
    };
    let l = crate::bus::layout::build_bus_layout(&sr, opts)
        .map_err(|e| format!("mega: layout {item}: {}", e.lines().next().unwrap_or("")))?;
    let adapted = adapt_boundaries(l)?;
    Ok((sr, adapted))
}

/// Re-pitch a layout's boundary inputs to the sim kit's 4-tile rig
/// pitch. Each input gets its own lateral LANE in the margin band, so
/// laterals never overlap each other; v1 refuses if a lateral would
/// cross another record's column or tail (not observed on the Phase-A
/// fixtures; the Router's hop machinery is the Phase-B answer if a
/// real subgraph ever needs it).
pub fn adapt_boundaries(l: LayoutResult) -> Result<LayoutResult, String> {
    let n_in = l.boundary_inputs.len() as i32;
    if n_in == 0 {
        return Err("mega: layout has no boundary inputs".into());
    }
    // One lateral lane per input + a clearance row above the original
    // north edge.
    let margin = n_in + 1;

    let mut entities: Vec<PlacedEntity> = l.entities.clone();
    for e in &mut entities {
        e.y += margin;
    }

    // Records sorted west→east (#363 rig-depth rule); heads assigned
    // at 4-pitch starting from the westmost original head.
    let mut records = l.boundary_inputs.clone();
    records.sort_by_key(|r| r.x);
    let head0 = records.first().map(|r| r.x).unwrap_or(1);

    // Plan first, stamp second: refuse crossings before emitting
    // anything. Lane i (row = 1 + i) belongs to record i alone; the
    // hazards are a lateral crossing another record's HEAD COLUMN
    // (x = head_x, rows 0..=lane_row) or TAIL column
    // (x = orig_x, rows lane_row..margin).
    struct Plan {
        head_x: i32,
        orig_x: i32,
        lane_row: i32,
        is_fluid: bool,
    }
    let plans: Vec<Plan> = records
        .iter()
        .enumerate()
        .map(|(i, r)| Plan {
            head_x: head0 + FEED_PITCH * i as i32,
            orig_x: r.x,
            lane_row: 1 + i as i32,
            is_fluid: r.is_fluid,
        })
        .collect();
    for (i, p) in plans.iter().enumerate() {
        let (lo, hi) = (p.head_x.min(p.orig_x), p.head_x.max(p.orig_x));
        for (j, q) in plans.iter().enumerate() {
            if i == j {
                continue;
            }
            // Another record's head column crosses my lateral row?
            let head_hits = q.head_x > lo && q.head_x < hi && q.lane_row > p.lane_row;
            // Another record's tail column crosses my lateral row?
            let tail_hits = q.orig_x > lo && q.orig_x < hi && q.lane_row < p.lane_row;
            if head_hits || tail_hits {
                return Err(format!(
                    "mega: boundary adapter v1 cannot route {} without crossing {}'s column (laterals {}..{} at row {})",
                    records[i].item, records[j].item, lo, hi, p.lane_row
                ));
            }
        }
    }

    // Fluid-occupancy map of the translated layout (pipes + PTG by
    // carried fluid): fluid feed paths must never sit orthogonally
    // adjacent to a DIFFERENT fluid (pipes merge by adjacency — the
    // sulfur fixture caught the naive tail doing exactly that against
    // the neighboring water column), and must END adjacent to a
    // SAME-fluid pipe (the join). Planned paths also register here so
    // records check against each other.
    let mut fluid_at: rustc_hash::FxHashMap<(i32, i32), String> = rustc_hash::FxHashMap::default();
    let mut solid_at: FxHashSet<(i32, i32)> = FxHashSet::default();
    for e in &entities {
        let is_pipe = e.name == "pipe" || e.name == "pipe-to-ground";
        if is_pipe {
            if let Some(f) = e.carries.as_deref() {
                fluid_at.insert((e.x, e.y), f.to_string());
            }
        } else {
            solid_at.insert((e.x, e.y));
        }
    }

    let neighbors = |x: i32, y: i32| [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)];

    let mut b_in: Vec<BoundaryRecord> = Vec::new();
    for (r, p) in records.iter().zip(plans.iter()) {
        let seg = format!("megafeed:{}", r.item);
        if p.is_fluid {
            // Plan the path with a candidate tail x: head column to the
            // lane row, lateral to tail_x, tail down to margin-1, plus a
            // JOIN tile at (tail_x, margin) when the tail is shifted off
            // the original head. Valid iff every tile is free, no
            // orthogonal neighbor carries a different fluid, and the
            // path ends adjacent to a same-fluid pipe.
            let mut chosen: Option<Vec<(i32, i32)>> = None;
            'cand: for dx in [0i32, 1, -1, 2, -2] {
                let tail_x = p.orig_x + dx;
                let mut tiles: Vec<(i32, i32)> = Vec::new();
                for y in 0..=p.lane_row {
                    tiles.push((p.head_x, y));
                }
                let (lo, hi) = (p.head_x.min(tail_x), p.head_x.max(tail_x));
                for x in lo..=hi {
                    if x != p.head_x {
                        tiles.push((x, p.lane_row));
                    }
                }
                for y in (p.lane_row + 1)..margin {
                    tiles.push((tail_x, y));
                }
                if dx != 0 {
                    tiles.push((tail_x, margin));
                }
                let tile_set: FxHashSet<(i32, i32)> = tiles.iter().copied().collect();
                for &(x, y) in &tiles {
                    if solid_at.contains(&(x, y)) || fluid_at.contains_key(&(x, y)) {
                        continue 'cand;
                    }
                    for n in neighbors(x, y) {
                        if tile_set.contains(&n) {
                            continue;
                        }
                        if let Some(f) = fluid_at.get(&n) {
                            if f != &r.item {
                                continue 'cand;
                            }
                        }
                    }
                }
                let last = *tiles.last().unwrap();
                let joins = neighbors(last.0, last.1).iter().any(|n| {
                    !tile_set.contains(n) && fluid_at.get(n).map(|f| f == &r.item).unwrap_or(false)
                });
                if !joins {
                    continue 'cand;
                }
                chosen = Some(tiles);
                break;
            }
            let tiles = chosen.ok_or_else(|| {
                format!(
                    "mega: no isolation-safe fluid feed path for {} (orig x {}, head x {}) — adapter v1 refuses",
                    r.item, p.orig_x, p.head_x
                )
            })?;
            for &(x, y) in &tiles {
                fluid_at.insert((x, y), r.item.clone());
                entities.push(PlacedEntity {
                    name: "pipe".into(),
                    x,
                    y,
                    direction: EntityDirection::North,
                    carries: Some(r.item.clone()),
                    segment_id: Some(seg.clone()),
                    ..Default::default()
                });
            }
        } else {
            // Belts: south column to the lane row; if re-pitched, a
            // lane-preserving corner toward the original x, then a
            // corner south and a tail column into the original head
            // (south belt feeding a south belt joins head-on).
            let mut push = |x: i32, y: i32, dir: EntityDirection| {
                solid_at.insert((x, y));
                entities.push(PlacedEntity {
                    name: r.entity.clone(),
                    x,
                    y,
                    direction: dir,
                    carries: Some(r.item.clone()),
                    segment_id: Some(seg.clone()),
                    ..Default::default()
                });
            };
            if p.head_x == p.orig_x {
                for y in 0..margin {
                    push(p.head_x, y, EntityDirection::South);
                }
            } else {
                for y in 0..p.lane_row {
                    push(p.head_x, y, EntityDirection::South);
                }
                let toward = if p.orig_x < p.head_x {
                    EntityDirection::West
                } else {
                    EntityDirection::East
                };
                let step = if p.orig_x < p.head_x { -1 } else { 1 };
                let mut x = p.head_x;
                while x != p.orig_x {
                    push(x, p.lane_row, toward);
                    x += step;
                }
                push(p.orig_x, p.lane_row, EntityDirection::South);
                for y in (p.lane_row + 1)..margin {
                    push(p.orig_x, y, EntityDirection::South);
                }
            }
        }
        b_in.push(BoundaryRecord {
            item: r.item.clone(),
            x: p.head_x,
            y: 0,
            direction: EntityDirection::South,
            is_fluid: r.is_fluid,
            entity: if p.is_fluid { "pipe".into() } else { r.entity.clone() },
        });
    }
    b_in.sort_by_key(|r| r.x);

    let b_out: Vec<BoundaryRecord> = l
        .boundary_outputs
        .iter()
        .map(|r| BoundaryRecord {
            y: r.y + margin,
            ..r.clone()
        })
        .collect();

    let width = entities.iter().map(|e| e.x).max().unwrap_or(0) + 1;
    let height = entities.iter().map(|e| e.y).max().unwrap_or(0) + 1;
    Ok(LayoutResult {
        entities,
        width,
        height,
        stacking: l.stacking,
        inserter_capacity: l.inserter_capacity,
        boundary_inputs: b_in,
        boundary_outputs: b_out,
        ..Default::default()
    })
}
