//! RFC-052 Phase A: oil mega-cells — the engine's own layout for a
//! fluid subgraph, used UNCROPPED as one composable unit.
//!
//! `extract_cell`'s segment crop is fatal for fluid complexes (it
//! sheds the inter-row fluid trunks — RFC-052 decision log), so a
//! mega-cell keeps the whole engine layout and attaches through its
//! own boundary records. Those records are already in the calibrated
//! orientation (north-edge south-flowing feeds, south-edge drains);
//! the one kit violation is FEED PITCH — the engine packs trunk heads
//! adjacent, the sim kit needs >=4 tiles between rigs (#363). The
//! adapter here re-pitches: translate the layout down a margin band,
//! give every boundary input a 4-pitch head at y=0, and route each
//! head through its OWN lane of the band into the original trunk head
//! (belts: column + lane-preserving corners; fluids: pipe runs, which
//! join by adjacency). Fluids never leave the mega-cell except at
//! these boundary records (RFC-052 design).

use rustc_hash::FxHashSet;

use crate::common::QualityTier;
use crate::models::{BoundaryRecord, EntityDirection, LayoutResult, PlacedEntity};
use crate::recipe_db::MachinePalette;
use crate::solver;

/// Sim-kit rig pitch (#363): adjacent feed rigs collide below 4.
const FEED_PITCH: i32 = 4;

/// Generate the engine layout for a fluid-subgraph target and adapt it
/// to the calibrated boundary form. Returns the sub-solve and the
/// adapted layout. Refuses (Err) on shapes the v1 adapter cannot route
/// without crossings — a loud refusal, never a silent overlap.
pub fn compose_mega_calibrated(
    item: &str,
    rate: f64,
    inputs: &[&str],
) -> Result<(crate::models::SolverResult, LayoutResult), String> {
    let inputs_set: FxHashSet<String> = inputs.iter().map(|s| s.to_string()).collect();
    let sr = solver::solve_with_palette_exclusions_and_quality(
        item,
        rate,
        &inputs_set,
        &MachinePalette::default(),
        "assembling-machine-3",
        &FxHashSet::default(),
        QualityTier::Normal,
    )
    .map_err(|e| format!("mega: solve {item}: {e}"))?;
    let opts = crate::bus::layout::LayoutOptions {
        // Cells are generated by the bus pipeline by definition (same
        // recursion guard as extract::generate_cell_layout).
        cell_composition: super::CellComposition::Off,
        ..Default::default()
    };
    let l = crate::bus::layout::build_bus_layout(&sr, opts)
        .map_err(|e| format!("mega: layout {item}: {}", e.lines().next().unwrap_or("")))?;
    let adapted = adapt_boundaries(l)?;
    Ok((sr, adapted))
}

/// Re-pitch a layout's boundary inputs to the sim kit's 4-tile rig
/// pitch. Each input gets its own lateral LANE in the margin band, so
/// laterals never overlap each other; v1 refuses if a lateral would
/// cross another record's column or tail (not observed on the Phase-A
/// fixtures; the Router's hop machinery is the Phase-B answer if a
/// real subgraph ever needs it).
pub fn adapt_boundaries(l: LayoutResult) -> Result<LayoutResult, String> {
    adapt_boundaries_chain_fed(l, &FxHashSet::default())
}

/// `chain_fed` (increment 2): items supplied by chain corridors, not
/// the outside world. Their records get NO head column — instead a
/// west-edge entry at (0, lane_row), each on its own lane row, so the
/// chain's delivery corridors approach on distinct rows.
pub fn adapt_boundaries_chain_fed(
    l: LayoutResult,
    chain_fed: &FxHashSet<String>,
) -> Result<LayoutResult, String> {
    // Lane spacing 1 first — bit-identical to the original adapter for
    // every fixture it could route (the registered hashes depend on
    // it). Spacing 2 unlocks 3+-fluid-feed blocks (the chem-pack
    // class), where a lateral otherwise passes directly under an
    // earlier head column with no clearance row.
    // Retry ladder: spacing 1 plain first (bit-identical for every
    // registered fixture), then the fluid-head DODGE at spacing 1
    // (relocates fluid head slots away from foreign fluid columns —
    // needed by blocks whose trunk heads pack adjacent, the USP
    // advanced complex), then spacing 2 in the same order.
    let mut last = String::new();
    for (spacing, dodge) in [(1, false), (1, true), (2, false), (2, true)] {
        match adapt_with_spacing(&l, spacing, chain_fed, dodge) {
            Ok(adapted) => return Ok(adapted),
            Err(e) => {
                if !last.is_empty() {
                    last.push_str("; ");
                }
                last.push_str(&format!("s{spacing}{}: {e}", if dodge { "+dodge" } else { "" }));
            }
        }
    }
    Err(last)
}

fn adapt_with_spacing(
    l: &LayoutResult,
    spacing: i32,
    chain_fed: &FxHashSet<String>,
    dodge_fluid_heads: bool,
) -> Result<LayoutResult, String> {
    let n_in = l.boundary_inputs.len() as i32;
    if n_in == 0 {
        return Err("mega: layout has no boundary inputs".into());
    }
    // One lateral lane per input (pitch `spacing`) + a clearance row
    // above the original north edge. Chain-fed records get ONE extra
    // clearance row: the deepest cf lateral sits at the old margin-1,
    // where a vertical retrofit's UG-out would land ON the engine head
    // row (Phase C, the USP advanced complex).
    let margin = (n_in - 1) * spacing + 2 + i32::from(!chain_fed.is_empty());

    let mut entities: Vec<PlacedEntity> = l.entities.clone();
    for e in &mut entities {
        e.y += margin;
    }

    // Records sorted west→east (#363 rig-depth rule); heads assigned
    // at 4-pitch starting from the westmost original head.
    // Chain-fed records (increment 2) sort LAST, eastmost-orig first:
    // they take the DEEPEST lanes, so no external head or tail column
    // (all of which bottom out at shallower external lane rows) ever
    // descends into a chain-fed lateral's row, and no chain-fed tail
    // (short: deep row to margin) reaches an external lateral. Every
    // residual crossing is a chain-fed LATERAL (always a solid belt)
    // over some column — resolved by UG hops at stamp time. Among
    // chain-fed records, east→west = shallow→deep keeps their own
    // (short) tails east of every deeper chain-fed lateral's span.
    let mut records = l.boundary_inputs.clone();
    let is_cf = |r: &BoundaryRecord| chain_fed.contains(&r.item);
    records.sort_by_key(|r| if is_cf(r) { (1, -r.x) } else { (0, r.x) });
    let head0 = records.first().map(|r| r.x).unwrap_or(1);

    // Plan first, stamp second: refuse crossings before emitting
    // anything. Lane i (row = 1 + i) belongs to record i alone; the
    // hazards are a lateral crossing another record's HEAD COLUMN
    // (x = head_x, rows 0..=lane_row) or TAIL column
    // (x = orig_x, rows lane_row..margin).
    struct Plan {
        head_x: i32,
        orig_x: i32,
        lane_row: i32,
        is_fluid: bool,
        west_entry: bool,
    }
    let mut n_heads = 0i32;
    // A FLUID head column descends through every shallower lateral row;
    // standing x-adjacent to a DIFFERENT fluid's orig or head column
    // makes a plain-plain side contact somewhere on the way down (the
    // USP advanced complex: the 4-pitch slot put water's head at
    // exactly its orig column 9, beside crude's orig 8 — every
    // candidate died on that adjacency). Fluid heads skip slots that
    // land within 1 of a foreign fluid column; solid heads don't care
    // (belts don't merge with pipes).
    let fluid_cols: Vec<i32> = records.iter().filter(|r| r.is_fluid).map(|r| r.x).collect();
    let mut fluid_heads: Vec<i32> = Vec::new();
    let plans: Vec<Plan> = records
        .iter()
        .enumerate()
        .map(|(i, r)| {
            let west_entry = is_cf(r);
            let head_x = if west_entry {
                0
            } else {
                let mut h = head0 + FEED_PITCH * n_heads;
                n_heads += 1;
                if r.is_fluid && dodge_fluid_heads {
                    let clashes = |h: i32| {
                        fluid_cols.iter().any(|&c| c != r.x && (h - c).abs() <= 1)
                            || fluid_heads.iter().any(|&c| (h - c).abs() <= 1)
                    };
                    while clashes(h) {
                        h = head0 + FEED_PITCH * n_heads;
                        n_heads += 1;
                    }
                    fluid_heads.push(h);
                }
                h
            };
            Plan {
                head_x,
                orig_x: r.x,
                lane_row: 1 + spacing * i as i32,
                is_fluid: r.is_fluid,
                west_entry,
            }
        })
        .collect();
    for (i, p) in plans.iter().enumerate() {
        if p.west_entry {
            // Chain-fed laterals resolve crossings with UG hops at
            // stamp time instead of refusing here.
            continue;
        }
        let (lo, hi) = (p.head_x.min(p.orig_x), p.head_x.max(p.orig_x));
        for (j, q) in plans.iter().enumerate() {
            if i == j {
                continue;
            }
            // Another record's head column crosses my lateral row?
            let head_hits = q.head_x > lo && q.head_x < hi && q.lane_row > p.lane_row;
            // Another record's tail column crosses my lateral row?
            let tail_hits = q.orig_x > lo && q.orig_x < hi && q.lane_row < p.lane_row;
            if head_hits || tail_hits {
                return Err(format!(
                    "mega: boundary adapter v1 cannot route {} without crossing {}'s column (laterals {}..{} at row {})",
                    records[i].item, records[j].item, lo, hi, p.lane_row
                ));
            }
        }
    }

    // Fluid-occupancy map of the translated layout (pipes + PTG by
    // carried fluid): fluid feed paths must never sit orthogonally
    // adjacent to a DIFFERENT fluid (pipes merge by adjacency — the
    // sulfur fixture caught the naive tail doing exactly that against
    // the neighboring water column), and must END adjacent to a
    // SAME-fluid pipe (the join). Planned paths also register here so
    // records check against each other.
    let mut fluid_at: rustc_hash::FxHashMap<(i32, i32), String> = rustc_hash::FxHashMap::default();
    let mut plain_pipe_at: FxHashSet<(i32, i32)> = FxHashSet::default();
    // Pipe-to-ground tiles are SIDE-SAFE: a mouth connects only along
    // its axis, so foreign-fluid adjacency against one is legal — the
    // original trunk heads are exactly such mouths (missing this made
    // the planner refuse approaches beside them).
    let mut ptg_at: FxHashSet<(i32, i32)> = FxHashSet::default();
    let mut solid_at: FxHashSet<(i32, i32)> = FxHashSet::default();
    for e in &entities {
        let is_pipe = e.name == "pipe" || e.name == "pipe-to-ground";
        if is_pipe {
            if let Some(f) = e.carries.as_deref() {
                fluid_at.insert((e.x, e.y), f.to_string());
                if e.name == "pipe" {
                    plain_pipe_at.insert((e.x, e.y));
                } else {
                    ptg_at.insert((e.x, e.y));
                }
            }
        } else {
            solid_at.insert((e.x, e.y));
        }
    }

    // Joint fluid planning (RFC-052 Phase B): with 3+ fluid feeds the
    // per-record greedy dead-ends — a shifted tail can land inside a
    // later record's lateral span (the chem-pack water refusal). Search
    // the dx-vector product across fluid records (≤10^F, F small),
    // evaluating sequentially against accumulated occupancy with early
    // abort; dx=0 first keeps the single/two-fluid fixtures on their
    // historical greedy solutions.
    let fluid_idx: Vec<usize> = plans
        .iter()
        .enumerate()
        .filter(|(_, p)| p.is_fluid)
        .map(|(i, _)| i)
        .collect();
    let mut fluid_paths: rustc_hash::FxHashMap<usize, FluidPath> =
        rustc_hash::FxHashMap::default();
    if !fluid_idx.is_empty() {
        // Candidate space per fluid record: 5 dx shifts × {plain, PTG
        // tail}. Plain variants come FIRST so every previously-solvable
        // block keeps its exact historical geometry (bit-identity).
        const CANDS: [(i32, bool); 10] = [
            (0, false), (1, false), (-1, false), (2, false), (-2, false),
            (0, true), (1, true), (-1, true), (2, true), (-2, true),
        ];
        let nf = fluid_idx.len();
        let mut combo = vec![0usize; nf];
        let mut found = false;
        'search: loop {
            // Evaluate this candidate-vector sequentially.
            let mut trial_fluid = fluid_at.clone();
            let mut trial_plain = plain_pipe_at.clone();
            let mut trial_ptg = ptg_at.clone();
            // Reserved UNDERGROUND span tiles (between a planned pair's
            // mouths, exclusive). Surface paths may cross them freely —
            // an underground run passes under surface pipes; only
            // same-axis underground interference is real. Registering
            // spans as surface occupiers refused every block whose
            // fluid trunk heads pack adjacent (the USP advanced
            // complex: crude at x=9, water at x=10).
            let mut trial_span: rustc_hash::FxHashMap<(i32, i32), String> =
                rustc_hash::FxHashMap::default();
            let mut trial_paths: rustc_hash::FxHashMap<usize, FluidPath> =
                rustc_hash::FxHashMap::default();
            let mut ok = true;
            for (k, &ri) in fluid_idx.iter().enumerate() {
                let r = &records[ri];
                let p = &plans[ri];
                let (dx, ptg) = CANDS[combo[k]];
                match try_fluid_path(
                    &r.item, p.head_x, p.orig_x, p.lane_row, dx, ptg, margin,
                    &solid_at, &trial_fluid, &trial_plain, &trial_ptg, &trial_span,
                ) {
                    Some(path) => {
                        for &(x, y) in &path.pipes {
                            trial_fluid.insert((x, y), r.item.clone());
                            trial_plain.insert((x, y));
                        }
                        if let Some((top, bot)) = path.ptg_pair {
                            // Mouths are surface PTG entities (side-safe,
                            // never plain); the strictly-interior span is
                            // underground only.
                            for (x, y) in [top, bot] {
                                trial_fluid.insert((x, y), r.item.clone());
                                trial_ptg.insert((x, y));
                            }
                            for y in (top.1 + 1)..bot.1 {
                                trial_span.insert((top.0, y), r.item.clone());
                            }
                        }
                        trial_paths.insert(ri, path);
                    }
                    None => {
                        ok = false;
                        break;
                    }
                }
            }
            if ok {
                fluid_paths = trial_paths;
                found = true;
                break 'search;
            }
            // Next combo (odometer).
            let mut k = nf;
            loop {
                if k == 0 {
                    break 'search;
                }
                k -= 1;
                combo[k] += 1;
                if combo[k] < CANDS.len() {
                    break;
                }
                combo[k] = 0;
            }
        }
        if !found {
            let items: Vec<&str> = fluid_idx.iter().map(|&i| records[i].item.as_str()).collect();
            return Err(format!(
                "mega: no isolation-safe joint routing for fluid feeds {items:?} — adapter refuses"
            ));
        }
    }

    let mut b_in: Vec<BoundaryRecord> = Vec::new();
    for (ri, (r, p)) in records.iter().zip(plans.iter()).enumerate() {
        let seg = format!("megafeed:{}", r.item);
        if p.is_fluid {
            // Path planned by the joint search above.
            let path = fluid_paths
                .remove(&ri)
                .ok_or_else(|| format!("mega: fluid path for {} missing from joint plan", r.item))?;
            for &(x, y) in &path.pipes {
                fluid_at.insert((x, y), r.item.clone());
                plain_pipe_at.insert((x, y));
                entities.push(PlacedEntity {
                    name: "pipe".into(),
                    x,
                    y,
                    direction: EntityDirection::North,
                    carries: Some(r.item.clone()),
                    segment_id: Some(seg.clone()),
                    ..Default::default()
                });
            }
            if let Some((top, bot)) = path.ptg_pair {
                // Vertical PTG pair, engine convention (#364: direction
                // = the underground-run side; the exporter flips to the
                // game's surface-opening form). Flow enters the top
                // mouth from the corner pipe above and exits
                // mouth-to-mouth into the trunk head below — the same
                // South-in/North-out pattern the fluid row templates
                // stamp.
                for ((x, y), dir, io) in [
                    (top, EntityDirection::South, "input"),
                    (bot, EntityDirection::North, "output"),
                ] {
                    fluid_at.insert((x, y), r.item.clone());
                    entities.push(PlacedEntity {
                        name: "pipe-to-ground".into(),
                        x,
                        y,
                        direction: dir,
                        io_type: Some(io.into()),
                        carries: Some(r.item.clone()),
                        segment_id: Some(seg.clone()),
                        ..Default::default()
                    });
                }
            }
        } else {
            // Belts: south column to the lane row; if re-pitched, a
            // lane-preserving corner toward the original x, then a
            // corner south and a tail column into the original head
            // (south belt feeding a south belt joins head-on).
            // Plan-then-stamp with an occupancy check, like the fluid
            // branch — the pre-check can't see fluid records'
            // dx-shifted tails, so belts verify their tiles too and
            // refuse loudly on conflict (#401 review finding 2).
            let mut path: Vec<(i32, i32, EntityDirection)> = Vec::new();
            let mut ug_mouths: Vec<(i32, i32, &str)> = Vec::new();
            if p.west_entry {
                // Chain-fed (increment 2): no head column. West-edge
                // entry at (0, lane_row) running east to the original
                // column, corner south, tail into the original head.
                // The chain corridor's eastbound approach into the
                // entry tile is a straight merge — both lanes. The
                // lateral UG-hops under every occupied column it
                // crosses (external tails, fluid tails, earlier
                // chain-fed tails — a solid belt hops under any of
                // them), same clustering as the chain Router.
                let mut occ_cols: FxHashSet<i32> = (1..p.orig_x)
                    .filter(|&x| {
                        solid_at.contains(&(x, p.lane_row))
                            || fluid_at.contains_key(&(x, p.lane_row))
                    })
                    .collect();
                let mut cols: Vec<i32> = occ_cols.iter().copied().collect();
                cols.sort_unstable();
                let mut clusters: Vec<(i32, i32)> = Vec::new();
                for c in cols {
                    match clusters.last_mut() {
                        Some((_, hi)) if c - *hi < 3 => *hi = c,
                        _ => clusters.push((c, c)),
                    }
                }
                // A cluster hops horizontally when both mouths fit
                // (entry >= 1 keeps the west-edge entry tile; exit
                // strictly west of the tail corner) within the
                // RECORD's belt-tier reach (the mouths stamp that
                // tier — a hardcoded express cap would let a yellow
                // record plan a pair the game never connects, #411
                // review). Un-hoppable clusters retrofit EVERY column
                // vertically instead: each crossing solid tail's belts
                // at our-row±1 become a South UG pair and the row
                // frees (the retrofit_feed_hop idiom; solid interior
                // columns only — never a corner, a pipe, or the engine
                // head row; refuse loudly otherwise).
                let ug_gap = crate::common::ug_max_reach(&r.entity) as i32;
                // Entry mouth may sit AT the west-edge entry tile
                // (x=0): the delivery corridor then feeds the UG
                // entrance head-on — a straight feed, both lanes.
                let hoppable = |lo2: i32, hi2: i32| {
                    lo2 >= 1 && hi2 + 1 < p.orig_x && hi2 - lo2 < ug_gap
                };
                let mut freed: FxHashSet<i32> = FxHashSet::default();
                for &(lo2, hi2) in &clusters {
                    if hoppable(lo2, hi2) {
                        continue;
                    }
                    for c in lo2..=hi2 {
                        if !occ_cols.contains(&c) {
                            continue;
                        }
                        let row = p.lane_row;
                        let owner = plans.iter().find(|q| q.orig_x == c && q.lane_row < row);
                        let interior =
                            owner.is_some_and(|q| row - 1 > q.lane_row) && row + 1 < margin;
                        let is_solid_col = solid_at.contains(&(c, row));
                        if !(interior && is_solid_col) {
                            return Err(format!(
                                "mega: chain-fed {} crossing at x={c} cannot hop or retrofit (row {}, interior={interior} solid={is_solid_col} fluid={:?} owner_lane={:?})",
                                r.item,
                                p.lane_row,
                                fluid_at.get(&(c, p.lane_row)),
                                owner.map(|q| q.lane_row)
                            ));
                        }
                        let mut converted = 0;
                        let mut removed = None;
                        for (idx, e) in entities.iter_mut().enumerate() {
                            if e.x != c || !e.name.contains("transport-belt") {
                                continue;
                            }
                            if e.y == row && e.direction == EntityDirection::South {
                                removed = Some(idx);
                            } else if (e.y == row - 1 || e.y == row + 1)
                                && e.direction == EntityDirection::South
                            {
                                e.name = e.name.replace("transport-belt", "underground-belt");
                                e.io_type =
                                    Some(if e.y == row - 1 { "input" } else { "output" }.into());
                                converted += 1;
                            }
                        }
                        match (converted, removed) {
                            (2, Some(idx)) => {
                                entities.remove(idx);
                                solid_at.remove(&(c, row));
                                occ_cols.remove(&c);
                                freed.insert(c);
                            }
                            _ => {
                                return Err(format!(
                                    "mega: chain-fed {} vertical retrofit at x={c} found {converted} belts (need 2) — adapter refuses",
                                    r.item
                                ));
                            }
                        }
                    }
                }
                // Re-cluster the surviving crossings and stamp hops.
                let mut cols: Vec<i32> = occ_cols.iter().copied().collect();
                cols.sort_unstable();
                let _ = &freed;
                let mut clusters: Vec<(i32, i32)> = Vec::new();
                for c in cols {
                    match clusters.last_mut() {
                        Some((_, hi)) if c - *hi < 3 => *hi = c,
                        _ => clusters.push((c, c)),
                    }
                }
                let mut x = 0;
                for (lo2, hi2) in clusters {
                    if !hoppable(lo2, hi2) {
                        return Err(format!(
                            "mega: chain-fed {} lateral cluster {}..{} unresolvable after retrofit",
                            r.item, lo2, hi2
                        ));
                    }
                    for xx in x..=(lo2 - 2) {
                        path.push((xx, p.lane_row, EntityDirection::East));
                    }
                    ug_mouths.push((lo2 - 1, p.lane_row, "input"));
                    ug_mouths.push((hi2 + 1, p.lane_row, "output"));
                    x = hi2 + 2;
                }
                for xx in x..p.orig_x {
                    path.push((xx, p.lane_row, EntityDirection::East));
                }
                for y in p.lane_row..margin {
                    path.push((p.orig_x, y, EntityDirection::South));
                }
            } else if p.head_x == p.orig_x {
                for y in 0..margin {
                    path.push((p.head_x, y, EntityDirection::South));
                }
            } else {
                for y in 0..p.lane_row {
                    path.push((p.head_x, y, EntityDirection::South));
                }
                let toward = if p.orig_x < p.head_x {
                    EntityDirection::West
                } else {
                    EntityDirection::East
                };
                let step = if p.orig_x < p.head_x { -1 } else { 1 };
                let mut x = p.head_x;
                while x != p.orig_x {
                    path.push((x, p.lane_row, toward));
                    x += step;
                }
                path.push((p.orig_x, p.lane_row, EntityDirection::South));
                for y in (p.lane_row + 1)..margin {
                    path.push((p.orig_x, y, EntityDirection::South));
                }
            }
            for &(x, y, _) in &path {
                if solid_at.contains(&(x, y)) || fluid_at.contains_key(&(x, y)) {
                    return Err(format!(
                        "mega: belt feed path for {} collides at ({x},{y}) — adapter v1 refuses",
                        r.item
                    ));
                }
            }
            for &(x, y, _) in &ug_mouths {
                if solid_at.contains(&(x, y)) || fluid_at.contains_key(&(x, y)) {
                    return Err(format!(
                        "mega: chain-fed {} hop mouth collides at ({x},{y}) — adapter refuses",
                        r.item
                    ));
                }
            }
            for (x, y, dir) in path {
                solid_at.insert((x, y));
                entities.push(PlacedEntity {
                    name: r.entity.clone(),
                    x,
                    y,
                    direction: dir,
                    carries: Some(r.item.clone()),
                    segment_id: Some(seg.clone()),
                    ..Default::default()
                });
            }
            for (x, y, io) in ug_mouths {
                solid_at.insert((x, y));
                entities.push(PlacedEntity {
                    name: r.entity.replace("transport-belt", "underground-belt"),
                    x,
                    y,
                    direction: EntityDirection::East,
                    io_type: Some(io.into()),
                    carries: Some(r.item.clone()),
                    segment_id: Some(seg.clone()),
                    ..Default::default()
                });
            }
        }
        b_in.push(BoundaryRecord {
            item: r.item.clone(),
            x: p.head_x,
            y: if p.west_entry { p.lane_row } else { 0 },
            direction: if p.west_entry {
                EntityDirection::East
            } else {
                EntityDirection::South
            },
            is_fluid: r.is_fluid,
            entity: if p.is_fluid { "pipe".into() } else { r.entity.clone() },
        });
    }
    b_in.sort_by_key(|r| r.x);

    let b_out: Vec<BoundaryRecord> = l
        .boundary_outputs
        .iter()
        .map(|r| BoundaryRecord {
            y: r.y + margin,
            ..r.clone()
        })
        .collect();

    let width = entities.iter().map(|e| e.x).max().unwrap_or(0) + 1;
    let height = entities.iter().map(|e| e.y).max().unwrap_or(0) + 1;
    Ok(LayoutResult {
        entities,
        width,
        height,
        stacking: l.stacking,
        inserter_capacity: l.inserter_capacity,
        boundary_inputs: b_in,
        boundary_outputs: b_out,
        // The engine's warnings survive the adaptation — dropping them
        // hid the ships-uncovered power note during #400's diagnosis.
        warnings: l.warnings.clone(),
        ..Default::default()
    })
}

/// One fluid feed path candidate for the joint planner: head column to
/// the lane row, lateral to `orig_x + dx`, tail descending (past the
/// band boundary when needed, up to 8 tiles) until an honest join —
/// same-fluid PLAIN pipe on any side, or a same-fluid pipe-to-ground
/// directly below (its axis opening; a PTG side never connects, #400's
/// lesson applied recursively). Valid iff every tile is free and no
/// orthogonal neighbor carries a DIFFERENT fluid.
/// A planned fluid feed: surface pipe tiles plus an optional vertical
/// PTG pair on the tail (mouths only; the underground span stays
/// entity-free but is reserved in the planner).
pub struct FluidPath {
    pub pipes: Vec<(i32, i32)>,
    /// (top mouth, bottom mouth) of a downward PTG pair, when the tail
    /// is rendered underground.
    pub ptg_pair: Option<((i32, i32), (i32, i32))>,
}

#[allow(clippy::too_many_arguments)]
fn try_fluid_path(
    item: &str,
    head_x: i32,
    orig_x: i32,
    lane_row: i32,
    dx: i32,
    ptg_tail: bool,
    margin: i32,
    solid_at: &FxHashSet<(i32, i32)>,
    fluid_at: &rustc_hash::FxHashMap<(i32, i32), String>,
    plain_pipe_at: &FxHashSet<(i32, i32)>,
    ptg_at: &FxHashSet<(i32, i32)>,
    span_at: &rustc_hash::FxHashMap<(i32, i32), String>,
) -> Option<FluidPath> {
    let neighbors = |x: i32, y: i32| [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)];
    let tail_x = orig_x + dx;
    for tail_depth in 0..=8i32 {
        let mut pipes: Vec<(i32, i32)> = Vec::new();
        for y in 0..=lane_row {
            pipes.push((head_x, y));
        }
        let (lo, hi) = (head_x.min(tail_x), head_x.max(tail_x));
        for x in lo..=hi {
            if x != head_x {
                pipes.push((x, lane_row));
            }
        }
        let deepest = if dx != 0 || tail_depth > 0 {
            margin + tail_depth - 1
        } else {
            margin - 1
        };
        // Tail rows lane_row+1..=deepest: plain pipes, or a vertical
        // PTG pair (RFC-052 PTG-hop increment). A PTG mouth has NO
        // side connections — sitting beside a foreign fluid column is
        // legal, which is exactly what unlocks blocks whose trunk
        // heads pack adjacent (the chem-pack class). Pair needs >= 2
        // tail rows; flow enters the top mouth from the corner pipe
        // above and exits mouth-to-mouth into the trunk head below.
        let tail_rows: Vec<i32> = ((lane_row + 1)..=deepest).collect();
        let mut ptg_pair: Option<((i32, i32), (i32, i32))> = None;
        if ptg_tail {
            if tail_rows.len() < 2 {
                return None;
            }
            // Underground reach: mouths at the extremes, so entity
            // distance = len-1. Refusing at distance > UG_PIPE_REACH
            // (the GAP cap, 9) is deliberately one tile conservative —
            // identical to the pre-#407 behavior, keeping registered
            // geometry stable while staying inside the game's
            // entity-distance-10 limit.
            if tail_rows.len() as i32 - 1 > crate::common::UG_PIPE_REACH as i32 {
                return None;
            }
            ptg_pair = Some((
                (tail_x, tail_rows[0]),
                (tail_x, *tail_rows.last().unwrap()),
            ));
        } else {
            for &y in &tail_rows {
                pipes.push((tail_x, y));
            }
        }
        let mouth_tiles: Vec<(i32, i32)> = ptg_pair
            .map(|(a, b)| vec![a, b])
            .unwrap_or_default();
        // All occupied tiles (surface pipes + mouths + reserved
        // underground span).
        let mut all_tiles: Vec<(i32, i32)> = pipes.clone();
        if ptg_pair.is_some() {
            for &y in &tail_rows {
                all_tiles.push((tail_x, y));
            }
        }
        let tile_set: FxHashSet<(i32, i32)> = all_tiles.iter().copied().collect();
        let dbg = std::env::var("SPAGHETTIO_MEGA_DEBUG").is_ok();
        let mut valid = true;
        'check: for &(x, y) in &all_tiles {
            let is_surface_pipe = pipes.contains(&(x, y));
            let is_mouth = mouth_tiles.contains(&(x, y));
            if !is_surface_pipe && !is_mouth {
                // Reserved underground span: passes freely under
                // surface entities (pipes, belts, machines); refuses
                // only same-axis underground interference — a foreign
                // span or a foreign surface PTG in this column (all
                // planned pairs and the original trunk heads are
                // vertical, so any such hit shares the axis and would
                // re-pair the mouths).
                if span_at.contains_key(&(x, y)) || ptg_at.contains(&(x, y)) {
                    if dbg { eprintln!("  [{item} dx={dx} ptg={ptg_tail} d={tail_depth}] span tile ({x},{y}) hits span/ptg"); }
                    valid = false;
                    break 'check;
                }
                continue;
            }
            if solid_at.contains(&(x, y)) || fluid_at.contains_key(&(x, y)) {
                if dbg { eprintln!("  [{item} dx={dx} ptg={ptg_tail} d={tail_depth}] tile ({x},{y}) solid={} fluid={:?}", solid_at.contains(&(x,y)), fluid_at.get(&(x,y))); }
                valid = false;
                break 'check;
            }
            if is_mouth && span_at.contains_key(&(x, y)) {
                // A surface mouth inside a foreign pair's underground
                // span would re-pair it (same axis).
                valid = false;
                break 'check;
            }
            if is_mouth {
                // Mouths connect axis-wise only; side adjacency to a
                // foreign fluid is legal. The AXIS neighbors (a mouth's
                // surface-connection side) are not re-checked here:
                // construction guarantees them — the top mouth connects
                // up into this record's own corner pipe and the bottom
                // mouth's join is gated by the `joins` predicate below,
                // both same-fluid by definition (#408 review).
                continue;
            }
            for n in neighbors(x, y) {
                if tile_set.contains(&n) {
                    continue;
                }
                if let Some(f) = fluid_at.get(&n) {
                    // Foreign PLAIN pipes merge on side contact; foreign
                    // PTG tiles (mouths/spans, incl. the original trunk
                    // heads) are side-safe.
                    if f != item && !ptg_at.contains(&n) {
                        if dbg { eprintln!("  [{item} dx={dx} ptg={ptg_tail} d={tail_depth}] tile ({x},{y}) adj ({},{}) foreign {f}", n.0, n.1); }
                        valid = false;
                        break 'check;
                    }
                }
            }
        }
        if !valid {
            // A deeper tail passes through the same blocked tile —
            // abandon this dx entirely.
            return None;
        }
        let terminus = (tail_x, deepest.max(lane_row));
        let joins = neighbors(terminus.0, terminus.1).iter().any(|n| {
            if tile_set.contains(n) {
                return false;
            }
            let Some(f) = fluid_at.get(n) else { return false };
            if f != item {
                return false;
            }
            // A PTG-tail terminus is the bottom MOUTH: it joins only
            // along its axis (directly below). Plain termini join a
            // plain pipe on any side or a PTG directly below.
            if ptg_pair.is_some() {
                return *n == (terminus.0, terminus.1 + 1);
            }
            plain_pipe_at.contains(n) || *n == (terminus.0, terminus.1 + 1)
        });
        if joins {
            return Some(FluidPath { pipes, ptg_pair });
        }
        if dbg {
            eprintln!("  [{item} dx={dx} ptg={ptg_tail} d={tail_depth}] terminus ({},{}) no join (fluid_at neighbors: {:?})",
                terminus.0, terminus.1,
                neighbors(terminus.0, terminus.1).iter().filter_map(|n| fluid_at.get(n).map(|f| (n.0, n.1, f.clone()))).collect::<Vec<_>>());
        }
    }
    None
}

/// RFC-052 Phase B: the fluid-subgraph partition. Identifies the
/// chain's fluid-touching specs and validates the v1 collapse rules:
/// one weakly-connected subgraph, solid-only edges to the rest of the
/// chain, external-only inputs, and exactly one solid output item
/// leaving it. Returns the mega sub-solve parameters or a named
/// refusal.
#[derive(Debug, Clone)]
pub struct MegaPlan {
    /// The subgraph's PRIMARY solid product (the sub-solve target —
    /// the highest-rate exported solid; the sub-solve pulls the other
    /// exports along as the same chain).
    pub target: String,
    /// Total chain rate of the target (per-machine rate × count).
    pub rate: f64,
    /// ALL solid items leaving the subgraph, with their chain rates —
    /// each gets its own drain/corridor (multi-output support: the
    /// chem-pack class exports plastic AND sulfur).
    pub outputs: Vec<(String, f64)>,
    /// External inputs the subgraph consumes (fluids + solids).
    pub inputs: Vec<String>,
    /// Solid inputs produced elsewhere in the CHAIN, with their total
    /// subgraph consumption rates (increment 2: the PU class — the
    /// subgraph swallows a spec that consumes chain-produced
    /// EC/AC/plates). Each becomes a chain corridor into the block's
    /// adapter feed head instead of an external.
    pub chain_fed: Vec<(String, f64)>,
    /// Recipes collapsed into the mega-cell.
    pub members: rustc_hash::FxHashSet<String>,
}

pub fn mega_subgraph(sr: &crate::models::SolverResult) -> Result<Option<MegaPlan>, String> {
    use rustc_hash::FxHashMap;
    let fluid_specs: Vec<&crate::models::MachineSpec> = sr
        .machines
        .iter()
        .filter(|m| {
            m.inputs.iter().any(|i| i.is_fluid) || m.outputs.iter().any(|o| o.is_fluid)
        })
        .collect();
    if fluid_specs.is_empty() {
        return Ok(None);
    }
    let members: FxHashSet<String> = fluid_specs.iter().map(|m| m.recipe.clone()).collect();
    let produced_anywhere: FxHashMap<&str, &str> = sr
        .machines
        .iter()
        .flat_map(|m| m.outputs.iter().map(move |o| (o.item.as_str(), m.recipe.as_str())))
        .collect();
    let in_subgraph =
        |recipe: &str| members.contains(recipe);

    // Weak connectivity over shared items among members.
    if fluid_specs.len() > 1 {
        let mut reached: FxHashSet<&str> = FxHashSet::default();
        let mut stack = vec![fluid_specs[0].recipe.as_str()];
        while let Some(r) = stack.pop() {
            if !reached.insert(r) {
                continue;
            }
            let spec = sr.machines.iter().find(|m| m.recipe == r).unwrap();
            for item in spec
                .inputs
                .iter()
                .map(|i| i.item.as_str())
                .chain(spec.outputs.iter().map(|o| o.item.as_str()))
            {
                for m in &fluid_specs {
                    if m.recipe != r
                        && (m.inputs.iter().any(|i| i.item == item)
                            || m.outputs.iter().any(|o| o.item == item))
                    {
                        stack.push(m.recipe.as_str());
                    }
                }
            }
        }
        if reached.len() != fluid_specs.len() {
            return Err(format!(
                "mega: {} fluid specs form {}+ disconnected subgraphs (v1 collapses exactly one)",
                fluid_specs.len(),
                2
            ));
        }
    }

    // Edges out must be solid; inputs from inside the chain refuse
    // (v1: the sub-solve must be self-contained on externals).
    let mut inputs: Vec<String> = Vec::new();
    let mut chain_fed: Vec<(String, f64)> = Vec::new();
    let mut solid_outputs: Vec<(&str, f64)> = Vec::new();
    for m in &fluid_specs {
        for i in &m.inputs {
            match produced_anywhere.get(i.item.as_str()) {
                Some(producer) if in_subgraph(producer) => {} // internal
                Some(_) => {
                    // Produced by a non-member chain spec (increment 2):
                    // fed by a chain corridor into the block's adapter
                    // head. Fluids never cross the boundary.
                    if i.is_fluid {
                        return Err(format!(
                            "mega: chain-fed input {} is a fluid (fluids never cross cell boundaries)",
                            i.item
                        ));
                    }
                    match chain_fed.iter_mut().find(|(x, _)| x == &i.item) {
                        Some((_, r)) => *r += i.rate * m.count,
                        None => chain_fed.push((i.item.clone(), i.rate * m.count)),
                    }
                }
                None => {
                    if !inputs.iter().any(|x| x == &i.item) {
                        inputs.push(i.item.clone());
                    }
                }
            }
        }
        for o in &m.outputs {
            let consumed_outside = sr.machines.iter().any(|c| {
                !in_subgraph(&c.recipe) && c.inputs.iter().any(|ci| ci.item == o.item)
            });
            let exported = sr.external_outputs.iter().any(|e| e.item == o.item);
            if consumed_outside || exported {
                if o.is_fluid {
                    return Err(format!(
                        "mega: fluid {} leaves the subgraph (fluids never cross cell boundaries)",
                        o.item
                    ));
                }
                solid_outputs.push((o.item.as_str(), o.rate * m.count));
            }
        }
    }
    if solid_outputs.is_empty() {
        return Err("mega: fluid subgraph has no solid output".into());
    }
    solid_outputs.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    Ok(Some(MegaPlan {
        target: solid_outputs[0].0.to_string(),
        rate: solid_outputs[0].1,
        outputs: solid_outputs
            .iter()
            .map(|(i, r)| (i.to_string(), *r))
            .collect(),
        inputs,
        chain_fed,
        members,
    }))
}

/// Phase-B block composer: the adapted mega layout at a rate share,
/// for placement as one chain slot. Generated from the PARENT chain's
/// OWN member specs (counts × scale) rather than a fresh single-target
/// re-solve — machine counts stay identical to the parent by
/// construction, and multi-output subgraphs (plastic AND sulfur
/// leaving one oil complex) get every export laid out and drained.
/// The block carries its own margin band and feed heads at its local
/// y=0.
pub fn compose_mega_block(
    sr: &crate::models::SolverResult,
    plan: &MegaPlan,
    scale: f64,
) -> Result<(crate::models::SolverResult, LayoutResult), String> {
    let machines: Vec<crate::models::MachineSpec> = sr
        .machines
        .iter()
        .filter(|m| plan.members.contains(&m.recipe))
        .map(|m| crate::models::MachineSpec {
            count: m.count * scale,
            ..m.clone()
        })
        .collect();
    let produced: FxHashSet<&str> = machines
        .iter()
        .flat_map(|m| m.outputs.iter().map(|o| o.item.as_str()))
        .collect();
    // External inputs of the SUBGRAPH at the scaled rate (per-machine
    // rates × scaled counts).
    let mut ext_in: rustc_hash::FxHashMap<String, (f64, bool)> = Default::default();
    for m in &machines {
        for i in &m.inputs {
            if !produced.contains(i.item.as_str()) {
                let e = ext_in.entry(i.item.clone()).or_insert((0.0, i.is_fluid));
                e.0 += i.rate * m.count;
            }
        }
    }
    let sub = crate::models::SolverResult {
        machines,
        external_inputs: ext_in
            .into_iter()
            .map(|(item, (rate, is_fluid))| crate::models::ItemFlow {
                item,
                rate,
                is_fluid,
                module_id: 0,
            })
            .collect(),
        external_outputs: plan
            .outputs
            .iter()
            .map(|(item, rate)| crate::models::ItemFlow {
                item: item.clone(),
                rate: rate * scale,
                is_fluid: false,
                module_id: 0,
            })
            .collect(),
        surplus_outputs: Vec::new(),
        dependency_order: sr
            .dependency_order
            .iter()
            .filter(|r| plan.members.contains(*r))
            .cloned()
            .collect(),
    };
    let opts = crate::bus::layout::LayoutOptions {
        cell_composition: super::CellComposition::Off,
        // Mega sub-solves pack every trunk span from y=0 (all inputs
        // are boundary heads), so tap splitters land on live neighbor
        // trunks and the zones don't bridge them — the spacer is the
        // fix (Phase C; main-line default stays off).
        splitter_tap_spacers: true,
        ..Default::default()
    };
    let l = crate::bus::layout::build_bus_layout(&sub, opts)
        .map_err(|e| format!("mega: block layout: {}", e.lines().next().unwrap_or("")))?;
    let cf: FxHashSet<String> = plan.chain_fed.iter().map(|(i, _)| i.clone()).collect();
    let adapted = adapt_boundaries_chain_fed(l, &cf)?;
    Ok((sub, adapted))
}
