//! [`LibraryLookup`] — placement engine that pulls existing entries from
//! [`crate::bus::balancer_library::balancer_templates`].
//!
//! This engine doesn't *place* anything — it returns a known-good
//! template if one exists for the requested `(n, m)` shape, or
//! [`PlacementError::ShapeNotAvailable`] otherwise. It serves as the
//! ground-truth baseline for benching engines that do real placement.
//!
//! Ignores the input [`BalancerGraph`] entirely: the library was
//! generated by Factorio-SAT's net-free mode, which discovers its own
//! topology. The recovered graph (via `bus::balancer_classify`) may not
//! match the synthesizer's canonical graph for the same shape.

use std::time::Instant;

use crate::balancer::placement::{
    PlacedTemplate, PlacedTemplateEntity, PlacementEngine, PlacementError, PlacementRequest,
    PlacementResult,
};
use crate::bus::balancer_library::{balancer_templates, BalancerTemplate};

#[derive(Debug, Default, Clone, Copy)]
pub struct LibraryLookup;

impl LibraryLookup {
    pub const fn new() -> Self {
        LibraryLookup
    }
}

impl PlacementEngine for LibraryLookup {
    fn name(&self) -> &'static str {
        "library_lookup"
    }

    fn place(&self, req: &PlacementRequest<'_>) -> Result<PlacementResult, PlacementError> {
        let started = Instant::now();
        let templates = balancer_templates();
        let template = templates
            .get(&(req.n, req.m))
            .ok_or(PlacementError::ShapeNotAvailable {
                n: req.n,
                m: req.m,
            })?;
        let solve_wall_ms = started.elapsed().as_millis() as u64;
        Ok(PlacementResult {
            template: to_placed_template(template),
            solve_wall_ms,
            engine_id: "library_lookup",
        })
    }
}

fn to_placed_template(t: &BalancerTemplate) -> PlacedTemplate {
    PlacedTemplate {
        n_inputs: t.n_inputs,
        n_outputs: t.n_outputs,
        width: t.width,
        height: t.height,
        entities: t
            .entities
            .iter()
            .map(|e| PlacedTemplateEntity {
                name: e.name.to_string(),
                x: e.x,
                y: e.y,
                direction: e.direction,
                io_type: e.io_type.map(str::to_string),
            })
            .collect(),
        input_tiles: t.input_tiles.to_vec(),
        output_tiles: t.output_tiles.to_vec(),
        source_blueprint: Some(t.source_blueprint.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::balancer::synth::synth;
    use std::time::Duration;

    #[test]
    fn library_lookup_finds_known_shapes() {
        let engine = LibraryLookup;
        let graph = synth(2, 2).unwrap();
        let req = PlacementRequest {
            graph: &graph,
            n: 2,
            m: 2,
            timeout: Duration::from_secs(1),
            seed: None,
        };
        let result = engine.place(&req).unwrap();
        assert_eq!(result.engine_id, "library_lookup");
        assert_eq!(result.template.n_inputs, 2);
        assert_eq!(result.template.n_outputs, 2);
        assert!(!result.template.entities.is_empty());
    }

    #[test]
    fn library_lookup_reports_missing_shapes() {
        let engine = LibraryLookup;
        let graph = synth(4, 9).unwrap();
        let req = PlacementRequest {
            graph: &graph,
            n: 4,
            m: 9,
            timeout: Duration::from_secs(1),
            seed: None,
        };
        match engine.place(&req) {
            Err(PlacementError::ShapeNotAvailable { n: 4, m: 9 }) => {}
            other => panic!("expected ShapeNotAvailable, got {:?}", other),
        }
    }
}
