"""Sync balancer templates from the Python library file to balancer_library.rs.

Reads source_blueprint strings from src/bus/balancer_library.py (generated by
generate_balancer_library.py) and calls `import_balancer` for any shapes not
already present in crates/core/src/bus/balancer_library.rs.

Called automatically by generate_balancer_library.py after generating templates.
Also safe to run standalone after manually editing the Python library file.

Usage:
    uv run python scripts/sync_balancer_to_rust.py
    uv run python scripts/sync_balancer_to_rust.py --dry-run
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).parent.parent
PY_LIB = REPO / "src" / "bus" / "balancer_library.py"
RUST_LIB = REPO / "crates" / "core" / "src" / "bus" / "balancer_library.rs"
MANIFEST = REPO / "crates" / "core" / "Cargo.toml"


def shapes_in_rust() -> set[tuple[int, int]]:
    """Return the set of (n_inputs, n_outputs) already present in the Rust library."""
    src = RUST_LIB.read_text()
    return {(int(m.group(1)), int(m.group(2))) for m in re.finditer(r"static T_(\d+)_(\d+)_ENTITIES", src)}


def load_py_templates() -> dict[tuple[int, int], str]:
    """Load {(n,m): source_blueprint} from the generated Python library file."""
    if not PY_LIB.exists():
        print(f"Python library not found: {PY_LIB}", file=sys.stderr)
        print("Run generate_balancer_library.py first.", file=sys.stderr)
        return {}
    spec = importlib.util.spec_from_file_location("_bal_py_sync", PY_LIB)
    if spec is None or spec.loader is None:
        return {}
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_bal_py_sync"] = mod
    spec.loader.exec_module(mod)
    return {k: t.source_blueprint for k, t in mod.BALANCER_TEMPLATES.items()}


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Sync Python balancer library to Rust")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be imported without modifying any file")
    args = parser.parse_args()

    templates = load_py_templates()
    if not templates:
        sys.exit(1)

    existing = shapes_in_rust()
    todo = sorted((n, m) for (n, m) in templates if (n, m) not in existing)

    print(f"Python library: {len(templates)} shapes | Rust library: {len(existing)} | new: {len(todo)}")
    if not todo:
        print("Nothing to import.")
        return

    # Build import_balancer once before the loop so subsequent invocations are instant.
    if not args.dry_run:
        print("Building import_balancer...", flush=True)
        subprocess.run(
            ["cargo", "build", "--manifest-path", str(MANIFEST), "--bin", "import_balancer", "--quiet"],
            cwd=str(REPO),
            check=True,
        )
    bin_path = REPO / "crates" / "core" / "target" / "debug" / "import_balancer"

    failed: list[tuple[int, int]] = []
    for n, m in todo:
        bp = templates[(n, m)]
        print(f"  Importing ({n},{m})...", end=" ", flush=True)
        if args.dry_run:
            print(f"[dry-run] {bp[:50]}...")
            continue
        result = subprocess.run([str(bin_path), bp], cwd=str(REPO), capture_output=True, text=True)
        if result.returncode != 0:
            print("FAILED")
            print(result.stderr, file=sys.stderr)
            failed.append((n, m))
        else:
            print("OK")

    if failed:
        print(f"\n{len(failed)} import(s) failed: {failed}", file=sys.stderr)
        sys.exit(1)
    elif not args.dry_run:
        print(f"\nDone. Imported {len(todo)} new shape(s) into {RUST_LIB.name}.")


if __name__ == "__main__":
    main()
