//! Short identifiers for items and machines used in compact URL fragments.
//!
//! Goal: shrink the `?in=iron-plate,copper-plate,…` part of layout URLs
//! while keeping the codes deterministic, mostly readable, and uniquely
//! decodable. Each slug gets a 3-char code by default; collisions are
//! resolved by escalating the colliding slugs to length 4, 5, ….
//!
//! The code for a slug is generated by walking the hyphen-separated words
//! round-robin: `iron-plate` → `i`, `p`, then `r`, → `ipr`. For single-word
//! slugs we just take the first N chars (`coal` → `coa`).
//!
//! **Snapshot stability**: the canonical table is committed at
//! `crates/core/data/short-ids.json` and embedded via `include_str!` so
//! the web app can import the same JSON instead of recomputing the table.
//! [`snapshot_matches_algorithm`] (a unit test) guarantees the snapshot
//! and the live algorithm agree — if a new recipe changes the table,
//! regenerate the snapshot with
//! `FUCKTORIO_UPDATE_SHORT_IDS=1 cargo test -p fucktorio_core short_ids`
//! and audit the diff for any URL-breaking shifts before committing.
//!
//! Belt names get hardcoded one-letter codes elsewhere (only three tiers,
//! easy to special-case); this module only handles items + machines.

use crate::recipe_db::db;
use rustc_hash::{FxHashMap, FxHashSet};
use std::collections::BTreeMap;
use std::sync::LazyLock;

/// Initial length to try for every slug. Most production items resolve at 3.
const BASE_LENGTH: usize = 3;

/// Hard cap on how far we'll escalate a single code before giving up.
/// Today the worst-case real-world collision needs 10; 16 leaves headroom
/// for future additions without making the cap a footgun.
const MAX_LENGTH: usize = 16;

/// Generate the deterministic round-robin code for `slug` at the requested
/// length. Single-word slugs get the first `length` chars; multi-word slugs
/// take 1 char from each word per pass and repeat until the buffer is full
/// or every word is exhausted.
fn round_robin_code(slug: &str, length: usize) -> String {
    let words: Vec<&str> = slug.split('-').filter(|w| !w.is_empty()).collect();
    if words.is_empty() {
        return String::new();
    }
    if words.len() == 1 {
        return words[0].chars().take(length).collect();
    }
    let word_chars: Vec<Vec<char>> = words.iter().map(|w| w.chars().collect()).collect();
    let mut out = String::with_capacity(length);
    let mut pos = 0;
    loop {
        let mut appended = false;
        for w in &word_chars {
            if out.chars().count() >= length {
                break;
            }
            if pos < w.len() {
                out.push(w[pos]);
                appended = true;
            }
        }
        if !appended || out.chars().count() >= length {
            break;
        }
        pos += 1;
    }
    out
}

/// Build a unique slug → short-code map for the given universe of slugs.
///
/// Starts every slug at length 3 and bumps colliders by 1 char until no
/// duplicates remain. Returns `Err(slugs)` if even at [`MAX_LENGTH`] some
/// slugs still share a code (effectively never — would require ≥ MAX_LENGTH
/// identical leading chars across word splits).
pub fn build_short_id_map(slugs: &[&str]) -> Result<FxHashMap<String, String>, Vec<String>> {
    // Sort + dedup for determinism. Two callers passing the same set in
    // different orders should get byte-identical maps.
    let mut universe: Vec<&str> = slugs.to_vec();
    universe.sort();
    universe.dedup();

    let mut length: FxHashMap<&str, usize> =
        universe.iter().map(|s| (*s, BASE_LENGTH)).collect();

    for _ in 0..=MAX_LENGTH {
        let mut by_code: FxHashMap<String, Vec<&str>> = FxHashMap::default();
        for slug in &universe {
            let code = round_robin_code(slug, length[slug]);
            by_code.entry(code).or_default().push(*slug);
        }
        let mut had_collision = false;
        for (_, owners) in by_code.iter() {
            if owners.len() > 1 {
                had_collision = true;
                for owner in owners {
                    if let Some(l) = length.get_mut(*owner) {
                        *l += 1;
                    }
                }
            }
        }
        if !had_collision {
            let out: FxHashMap<String, String> = universe
                .iter()
                .map(|s| (s.to_string(), round_robin_code(s, length[*s])))
                .collect();
            return Ok(out);
        }
    }

    // Couldn't converge — return the slugs that still collide so callers
    // can report which pair busted the algorithm.
    let mut by_code: FxHashMap<String, Vec<&str>> = FxHashMap::default();
    for slug in &universe {
        let code = round_robin_code(slug, length[slug].min(MAX_LENGTH));
        by_code.entry(code).or_default().push(*slug);
    }
    let stuck: Vec<String> = by_code
        .into_iter()
        .filter(|(_, owners)| owners.len() > 1)
        .flat_map(|(_, owners)| owners.into_iter().map(String::from))
        .collect();
    Err(stuck)
}

/// Universe of slugs the short-id table covers: every item that appears as
/// a recipe ingredient or product, plus every machine entity. Sorted +
/// deduped so the table is identical across runs.
///
/// Also the input the web app feeds to its TS port of the algorithm — both
/// sides must use the same universe to produce identical codes.
pub fn known_slugs() -> Vec<String> {
    let mut set: FxHashSet<String> = FxHashSet::default();
    for recipe in db().recipes.values() {
        for ing in &recipe.ingredients {
            set.insert(ing.name.clone());
        }
        for prod in &recipe.products {
            set.insert(prod.name.clone());
        }
    }
    for machine in db().machines.keys() {
        set.insert(machine.clone());
    }
    let mut out: Vec<String> = set.into_iter().collect();
    out.sort();
    out
}

/// Forward (slug → code) and reverse (code → slug) tables. Built lazily
/// once on first access. If the algorithm fails to converge — which the
/// unit test rules out for the current recipe data — this panics so the
/// problem surfaces at the first call rather than silently returning
/// `None` for the affected slugs.
struct Tables {
    forward: FxHashMap<String, String>,
    reverse: FxHashMap<String, String>,
}

static TABLES: LazyLock<Tables> = LazyLock::new(|| {
    let slugs = known_slugs();
    let slug_refs: Vec<&str> = slugs.iter().map(|s| s.as_str()).collect();
    let forward = build_short_id_map(&slug_refs)
        .expect("short-id algorithm failed to converge — see short_ids tests");
    let reverse = forward
        .iter()
        .map(|(slug, code)| (code.clone(), slug.clone()))
        .collect();
    Tables { forward, reverse }
});

/// Look up the short code for a slug, if it's in the universe.
pub fn short_id_for_slug(slug: &str) -> Option<&'static str> {
    TABLES.forward.get(slug).map(|s| s.as_str())
}

/// Look up the slug for a short code, if it's known.
pub fn slug_for_short_id(code: &str) -> Option<&'static str> {
    TABLES.reverse.get(code).map(|s| s.as_str())
}

/// Snapshot of the entire short-id table — slug → code. Cloned on each
/// call; cheap because the underlying static map isn't mutated.
pub fn short_id_table() -> &'static FxHashMap<String, String> {
    &TABLES.forward
}

/// Canonical, committable JSON form of the slug→code table. Sorted by
/// slug so diffs are stable across regenerations.
///
/// The web app imports the same JSON file (`crates/core/data/short-ids.json`)
/// and reads `codes` directly, so both sides agree on every code without
/// either re-running the algorithm.
pub fn short_id_snapshot_json() -> String {
    let codes: BTreeMap<String, String> = TABLES
        .forward
        .iter()
        .map(|(slug, code)| (slug.clone(), code.clone()))
        .collect();
    let snapshot = serde_json::json!({
        "version": 1,
        "codes": codes,
    });
    let mut out = serde_json::to_string_pretty(&snapshot)
        .expect("BTreeMap<String, String> serialises losslessly");
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_robin_examples() {
        assert_eq!(round_robin_code("iron-plate", 3), "ipr");
        assert_eq!(round_robin_code("iron-ore", 3), "ior");
        assert_eq!(round_robin_code("iron-gear-wheel", 3), "igw");
        assert_eq!(round_robin_code("coal", 3), "coa");
        assert_eq!(round_robin_code("water", 3), "wat");
        assert_eq!(round_robin_code("assembling-machine-1", 3), "am1");
        assert_eq!(round_robin_code("crude-oil", 3), "cor");
        // Length escalation extends each word in turn.
        assert_eq!(round_robin_code("iron-plate", 4), "iprl");
        assert_eq!(round_robin_code("iron-plate", 5), "iprlo");
    }

    #[test]
    fn round_robin_handles_short_words() {
        // "uranium-235": once "235" is exhausted we keep pulling from
        // "uranium" until we have enough chars.
        let code = round_robin_code("uranium-235", 5);
        assert_eq!(code, "u2r3a");
    }

    #[test]
    fn build_map_no_collisions_on_recipe_universe() {
        let slugs = known_slugs();
        let slug_refs: Vec<&str> = slugs.iter().map(|s| s.as_str()).collect();
        let map = build_short_id_map(&slug_refs)
            .expect("recipe universe should converge well below MAX_LENGTH");

        assert_eq!(map.len(), slugs.len(), "every slug should get a code");

        let unique_codes: FxHashSet<&String> = map.values().collect();
        assert_eq!(
            unique_codes.len(),
            map.len(),
            "all codes must be unique across the universe"
        );
    }

    #[test]
    fn build_map_is_deterministic() {
        let slugs = known_slugs();
        let slug_refs: Vec<&str> = slugs.iter().map(|s| s.as_str()).collect();
        let a = build_short_id_map(&slug_refs).unwrap();
        let b = build_short_id_map(&slug_refs).unwrap();
        assert_eq!(a, b);

        // Permuting input order must not change output.
        let mut shuffled: Vec<&str> = slug_refs.clone();
        shuffled.reverse();
        let c = build_short_id_map(&shuffled).unwrap();
        assert_eq!(a, c);
    }

    #[test]
    fn round_trip_lookup() {
        for (slug, code) in short_id_table() {
            assert_eq!(slug_for_short_id(code), Some(slug.as_str()));
            assert_eq!(short_id_for_slug(slug), Some(code.as_str()));
        }
    }

    #[test]
    fn most_codes_stay_short() {
        // Sanity: the algorithm shouldn't blow out lengths for the common
        // case. Today the recipe DB resolves with > 75% of codes at length
        // 3 and a max length well below 16. If a future recipe addition
        // pushes us past these thresholds, that's worth a conscious look.
        let table = short_id_table();
        let total = table.len();
        let len3 = table.values().filter(|c| c.len() == 3).count();
        assert!(
            len3 * 4 >= total * 3,
            "expected >=75% of codes at length 3, got {}/{}",
            len3,
            total
        );
        let max_len = table.values().map(|c| c.len()).max().unwrap_or(0);
        assert!(max_len <= 12, "max code length grew to {max_len}");
    }

    #[test]
    fn known_factorio_codes() {
        // Anchor a handful of well-known slugs so a future algorithm tweak
        // can't silently shift them. If you change the algorithm and these
        // need updating, audit the URL-stability story before doing so.
        assert_eq!(short_id_for_slug("iron-plate"), Some("ipr"));
        assert_eq!(short_id_for_slug("copper-plate"), Some("cpo"));
        assert_eq!(short_id_for_slug("iron-gear-wheel"), Some("igw"));
        assert_eq!(short_id_for_slug("electronic-circuit"), Some("ecl"));
        assert_eq!(short_id_for_slug("advanced-circuit"), Some("acd"));
        assert_eq!(short_id_for_slug("processing-unit"), Some("pur"));
        assert_eq!(short_id_for_slug("water"), Some("wat"));
        assert_eq!(short_id_for_slug("coal"), Some("coa"));
        assert_eq!(short_id_for_slug("assembling-machine-3"), Some("am3"));
    }

    /// The canonical short-id table is committed at
    /// `crates/core/data/short-ids.json`. This test fails if the live
    /// algorithm output disagrees — i.e. someone added a new recipe or
    /// touched the algorithm without regenerating the snapshot.
    ///
    /// To regenerate the file:
    ///
    ///   FUCKTORIO_UPDATE_SHORT_IDS=1 cargo test -p fucktorio_core \
    ///       --lib short_ids::tests::snapshot_matches_algorithm
    ///
    /// Then audit the diff: any code that *shifted* (rather than a new
    /// row appearing) breaks every URL that used the old code.
    #[test]
    fn snapshot_matches_algorithm() {
        const SNAPSHOT_RAW: &str = include_str!("../data/short-ids.json");
        let expected = short_id_snapshot_json();

        if std::env::var("FUCKTORIO_UPDATE_SHORT_IDS").is_ok() {
            let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("data")
                .join("short-ids.json");
            std::fs::write(&path, &expected).expect("write short-ids.json");
            // Re-run without the env var to verify the freshly written
            // file matches — catches accidental non-determinism.
            assert_eq!(
                std::fs::read_to_string(&path).unwrap(),
                expected,
                "freshly written snapshot disagrees with itself"
            );
            return;
        }

        assert_eq!(
            SNAPSHOT_RAW, expected,
            "short-ids.json is stale; rerun with \
             FUCKTORIO_UPDATE_SHORT_IDS=1 cargo test short_ids::tests::snapshot_matches_algorithm \
             to regenerate, then audit the diff for URL-breaking shifts"
        );
    }
}
