//! Persistent + in-memory cache of SAT crossing-zone solutions.
//!
//! Cache file is `sat-zones.bin` (binary records — see `encode_record`).
//! Native builds read/write to `$XDG_CACHE_HOME/fucktorio/sat-zones.bin`
//! (or `FUCKTORIO_ZONE_CACHE_PATH` override); WASM builds load a pre-baked
//! blob via `include_bytes!` instead and never write to disk.
//!
//! The signature captures port connectivity (grouped by channel_id),
//! forbidden interior tiles, per-channel UG reach, and the `max_ug_ins`
//! cap. Two zones with the same signature have identical SAT problems, so
//! a cached solution from one is valid for the other (modulo D4 replay
//! handled by [`lookup_zone`]).
//!
//! Code split: parser, lookup, transforms, and `install_prebaked` are
//! always available. File I/O (`flush`, `load_existing_jsonl`,
//! `resolve_cache_path`, `pending_count`) is gated behind
//! `#[cfg(not(target_arch = "wasm32"))]`.

use crate::models::{EntityDirection, PlacedEntity};
use crate::sat::CrossingZone;

/// Pre-baked cache embedded in WASM builds. Generated by running
/// `diag_corpus_sweep` against the e2e corpus and copying
/// `~/.cache/fucktorio/sat-zones.bin` to `crates/core/data/`.
#[cfg(target_arch = "wasm32")]
const EMBEDDED_CACHE: &[u8] = include_bytes!("../data/sat-zones.bin");

/// Internal edge classification used only for the canonical signature
/// computation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Edge {
    N,
    E,
    S,
    W,
}

/// Derive `(edge, offset)` for a port at `(px, py)` on the boundary of a
/// `(width, height)` zone anchored at `(zx, zy)`. Returns `None` if the
/// port point is outside the zone bbox.
fn edge_and_offset(
    zx: i32,
    zy: i32,
    w: u32,
    h: u32,
    px: i32,
    py: i32,
    fallback_dir: crate::models::EntityDirection,
) -> Option<(Edge, u32)> {
    let lx = px - zx;
    let ly = py - zy;
    if lx < 0 || ly < 0 || lx as u32 >= w || ly as u32 >= h {
        return None;
    }
    let lxu = lx as u32;
    let lyu = ly as u32;
    let on_north = lyu == 0;
    let on_south = lyu == h - 1;
    let on_west = lxu == 0;
    let on_east = lxu == w - 1;
    let edge = match (on_north, on_south, on_west, on_east) {
        (true, false, false, false) => Edge::N,
        (false, true, false, false) => Edge::S,
        (false, false, true, false) => Edge::W,
        (false, false, false, true) => Edge::E,
        // Corner/degenerate — break ties with flow direction.
        _ => {
            use crate::models::EntityDirection;
            match fallback_dir {
                EntityDirection::North => Edge::N,
                EntityDirection::South => Edge::S,
                EntityDirection::West => Edge::W,
                EntityDirection::East => Edge::E,
            }
        }
    };
    let offset = match edge {
        Edge::N | Edge::S => lxu,
        Edge::E | Edge::W => lyu,
    };
    Some((edge, offset))
}

/// SAT solver stats associated with a zone record. Mirrors
/// `sat::CrossingZoneStats` but kept local so `zone_cache` doesn't depend on
/// the full `sat` module's stats type for callers that just want to record.
pub struct ZoneStats {
    pub variables: u32,
    pub clauses: u32,
    pub solve_time_us: u64,
}
use std::cell::RefCell;
#[cfg(not(target_arch = "wasm32"))]
use std::io::Write as _;
use std::sync::{Mutex, OnceLock};
use std::time::{SystemTime, UNIX_EPOCH};

// Thread-local source tag so parallel tests each carry their own label
// without stomping on each other via a process-global env var.
thread_local! {
    static ZONE_SOURCE: RefCell<Option<String>> = const { RefCell::new(None) };
}

/// Per-zone record buffered between flushes. Stored serialised because
/// One pre-encoded binary record (length prefix + body), ready to write.
/// Encoding eagerly keeps the lock-held critical section to a `Vec::push`.
#[cfg(not(target_arch = "wasm32"))]
struct PendingRecord {
    bytes: Vec<u8>,
}

/// Process-global record buffer. Records are appended via `record_zone_with_solution`
/// and drained by `flush`. WASM has no buffer (no flush target).
#[cfg(not(target_arch = "wasm32"))]
static BUFFER: OnceLock<Mutex<Vec<PendingRecord>>> = OnceLock::new();

#[cfg(not(target_arch = "wasm32"))]
fn buffer() -> &'static Mutex<Vec<PendingRecord>> {
    BUFFER.get_or_init(|| Mutex::new(Vec::new()))
}

/// Set the per-thread zone source tag. Call this at the start of a test body.
pub fn set_thread_source(source: Option<&str>) {
    ZONE_SOURCE.with(|s| *s.borrow_mut() = source.map(|s| s.to_string()));
}

/// Resolve the binary cache file path. Format suffix is `.bin` (binary
/// records) — older `.jsonl` files in the same dir are still read at load
/// time for backward compat, but new writes only go to `.bin`.
#[cfg(not(target_arch = "wasm32"))]
fn resolve_cache_path() -> std::path::PathBuf {
    if let Ok(p) = std::env::var("FUCKTORIO_ZONE_CACHE_PATH") {
        return std::path::PathBuf::from(p);
    }
    let base = std::env::var("XDG_CACHE_HOME")
        .ok()
        .filter(|s| !s.is_empty())
        .map(std::path::PathBuf::from)
        .or_else(|| {
            std::env::var("HOME")
                .ok()
                .map(|h| std::path::PathBuf::from(h).join(".cache"))
        })
        .unwrap_or_else(|| std::path::PathBuf::from(".cache"));
    base.join("fucktorio").join("sat-zones.bin")
}

/// Legacy JSONL path — read for backward compat, never written.
#[cfg(not(target_arch = "wasm32"))]
fn resolve_legacy_jsonl_path() -> std::path::PathBuf {
    let bin = resolve_cache_path();
    bin.with_extension("jsonl")
}

// ---------------------------------------------------------------------------
// Canonical orientation-invariant signature
// ---------------------------------------------------------------------------

/// Apply a D4 transform (rotation × reflection) to an `(edge, offset)` pair
/// in a `(w, h)` zone, returning the post-transform `(edge, offset, new_w, new_h)`.
///
/// `edge`: 0=N, 1=E, 2=S, 3=W. `rotation` in 0..4 (90° CW each), `reflect`
/// applied first (vertical-axis flip).
fn transform_port(
    edge: u8,
    offset: u32,
    w: u32,
    h: u32,
    rotation: u8,
    reflect: bool,
) -> (u8, u32, u32, u32) {
    let (edge, offset) = if reflect {
        match edge {
            0 => (0u8, w.saturating_sub(1).saturating_sub(offset)),
            1 => (3u8, offset),
            2 => (2u8, w.saturating_sub(1).saturating_sub(offset)),
            3 => (1u8, offset),
            _ => (edge, offset),
        }
    } else {
        (edge, offset)
    };

    let mut e = edge;
    let mut o = offset;
    let mut cur_w = w;
    let mut cur_h = h;
    for _ in 0..rotation {
        let (ne, no) = match e {
            0 => (1u8, o),
            1 => (2u8, cur_w.saturating_sub(1).saturating_sub(o)),
            2 => (3u8, cur_h.saturating_sub(1).saturating_sub(o)),
            3 => (0u8, o),
            _ => (e, o),
        };
        e = ne;
        o = no;
        std::mem::swap(&mut cur_w, &mut cur_h);
    }

    (e, o, cur_w, cur_h)
}

/// Apply a D4 transform to a local `(x, y)` tile in a `(w, h)` zone.
/// Reflection (vertical-axis flip) applied first, then `rotation` 90° CW
/// rotations. Returns position in the post-transform frame.
fn transform_tile(x: u32, y: u32, w: u32, h: u32, rotation: u8, reflect: bool) -> (u32, u32) {
    let (mut tx, mut ty) = if reflect {
        (w.saturating_sub(1).saturating_sub(x), y)
    } else {
        (x, y)
    };
    let mut cur_w = w;
    let mut cur_h = h;
    for _ in 0..rotation {
        // 90° CW: (x, y) in (w, h) → (h - 1 - y, x) in (h, w)
        let (nx, ny) = (cur_h.saturating_sub(1).saturating_sub(ty), tx);
        tx = nx;
        ty = ny;
        std::mem::swap(&mut cur_w, &mut cur_h);
    }
    (tx, ty)
}

/// Invert [`transform_tile`]. Given a tile in the post-transform `(tw, th)`
/// frame, return its position in the original `(w, h)` frame.
///
/// `T = R^rot ∘ Refl^refl` (refl first, then rot), so `T⁻¹ = Refl ∘ R^(4-rot)`:
/// rotate by `(4-rot)%4` 90° CW first, then apply reflect (involution).
fn transform_tile_inverse(x: u32, y: u32, tw: u32, th: u32, rotation: u8, reflect: bool) -> (u32, u32) {
    let inv_rot = (4 - rotation) % 4;
    let mut tx = x;
    let mut ty = y;
    let mut cur_w = tw;
    let mut cur_h = th;
    for _ in 0..inv_rot {
        let (nx, ny) = (cur_h.saturating_sub(1).saturating_sub(ty), tx);
        tx = nx;
        ty = ny;
        std::mem::swap(&mut cur_w, &mut cur_h);
    }
    if reflect {
        tx = cur_w.saturating_sub(1).saturating_sub(tx);
    }
    (tx, ty)
}

/// Apply a D4 transform to an `EntityDirection`. Reflection first
/// (vertical-axis flip: E↔W, N/S unchanged), then `rotation` 90° CW rotations
/// (N→E→S→W→N).
fn transform_direction(d: EntityDirection, rotation: u8, reflect: bool) -> EntityDirection {
    let d = if reflect {
        match d {
            EntityDirection::East => EntityDirection::West,
            EntityDirection::West => EntityDirection::East,
            other => other,
        }
    } else {
        d
    };
    let mut d = d;
    for _ in 0..rotation {
        d = match d {
            EntityDirection::North => EntityDirection::East,
            EntityDirection::East => EntityDirection::South,
            EntityDirection::South => EntityDirection::West,
            EntityDirection::West => EntityDirection::North,
        };
    }
    d
}

/// Invert [`transform_direction`].
fn transform_direction_inverse(d: EntityDirection, rotation: u8, reflect: bool) -> EntityDirection {
    let inv_rot = (4 - rotation) % 4;
    let mut d = d;
    for _ in 0..inv_rot {
        d = match d {
            EntityDirection::North => EntityDirection::East,
            EntityDirection::East => EntityDirection::South,
            EntityDirection::South => EntityDirection::West,
            EntityDirection::West => EntityDirection::North,
        };
    }
    if reflect {
        d = match d {
            EntityDirection::East => EntityDirection::West,
            EntityDirection::West => EntityDirection::East,
            other => other,
        };
    }
    d
}

/// Apply the D4 transform `(rotation, reflect)` to an entity. Input is
/// expected in zone-local coords (i.e. `entity.x` ∈ `[0, w)`); output is in
/// the post-transform frame (size `(tw, th)`).
///
/// Belts, undergrounds, splitters and any other 1×1 entity work cleanly here.
/// The cache scope only covers SAT-produced junction entities, all of which
/// are 1×1, so multi-tile entity rotation isn't a concern.
fn transform_entity(
    entity: &PlacedEntity,
    w: u32,
    h: u32,
    rotation: u8,
    reflect: bool,
) -> PlacedEntity {
    let (nx, ny) = transform_tile(entity.x as u32, entity.y as u32, w, h, rotation, reflect);
    let mut out = entity.clone();
    out.x = nx as i32;
    out.y = ny as i32;
    out.direction = transform_direction(entity.direction, rotation, reflect);
    out
}

/// Inverse of [`transform_entity`]. Input is in the post-transform frame
/// (size `(tw, th)`); output is in the original frame.
fn transform_entity_inverse(
    entity: &PlacedEntity,
    tw: u32,
    th: u32,
    rotation: u8,
    reflect: bool,
) -> PlacedEntity {
    let (nx, ny) = transform_tile_inverse(entity.x as u32, entity.y as u32, tw, th, rotation, reflect);
    let mut out = entity.clone();
    out.x = nx as i32;
    out.y = ny as i32;
    out.direction = transform_direction_inverse(entity.direction, rotation, reflect);
    out
}

// ---------------------------------------------------------------------------
// Compact entity encoding for the JSONL solution cache
// ---------------------------------------------------------------------------

/// Packed entity-kind: belt tier × (surface | UG-in | UG-out). Junction SAT
/// only ever produces these 9 kinds, so a single small int per entity is
/// enough to round-trip name + io_type.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EntityKind {
    BeltYellow = 0,
    BeltRed = 1,
    BeltBlue = 2,
    UgInYellow = 3,
    UgOutYellow = 4,
    UgInRed = 5,
    UgOutRed = 6,
    UgInBlue = 7,
    UgOutBlue = 8,
}

impl EntityKind {
    fn from_entity(e: &PlacedEntity) -> Option<Self> {
        let io = e.io_type.as_deref();
        match (e.name.as_str(), io) {
            ("transport-belt", None | Some("passthrough")) => Some(Self::BeltYellow),
            ("fast-transport-belt", None | Some("passthrough")) => Some(Self::BeltRed),
            ("express-transport-belt", None | Some("passthrough")) => Some(Self::BeltBlue),
            ("underground-belt", Some("input")) => Some(Self::UgInYellow),
            ("underground-belt", Some("output")) => Some(Self::UgOutYellow),
            ("fast-underground-belt", Some("input")) => Some(Self::UgInRed),
            ("fast-underground-belt", Some("output")) => Some(Self::UgOutRed),
            ("express-underground-belt", Some("input")) => Some(Self::UgInBlue),
            ("express-underground-belt", Some("output")) => Some(Self::UgOutBlue),
            _ => None,
        }
    }

    fn name_and_io(self) -> (&'static str, Option<&'static str>) {
        match self {
            Self::BeltYellow => ("transport-belt", None),
            Self::BeltRed => ("fast-transport-belt", None),
            Self::BeltBlue => ("express-transport-belt", None),
            Self::UgInYellow => ("underground-belt", Some("input")),
            Self::UgOutYellow => ("underground-belt", Some("output")),
            Self::UgInRed => ("fast-underground-belt", Some("input")),
            Self::UgOutRed => ("fast-underground-belt", Some("output")),
            Self::UgInBlue => ("express-underground-belt", Some("input")),
            Self::UgOutBlue => ("express-underground-belt", Some("output")),
        }
    }

    fn from_u8(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::BeltYellow),
            1 => Some(Self::BeltRed),
            2 => Some(Self::BeltBlue),
            3 => Some(Self::UgInYellow),
            4 => Some(Self::UgOutYellow),
            5 => Some(Self::UgInRed),
            6 => Some(Self::UgOutRed),
            7 => Some(Self::UgInBlue),
            8 => Some(Self::UgOutBlue),
            _ => None,
        }
    }
}

fn dir_to_u8(d: EntityDirection) -> u8 {
    match d {
        EntityDirection::North => 0,
        EntityDirection::East => 1,
        EntityDirection::South => 2,
        EntityDirection::West => 3,
    }
}

fn dir_from_u8(v: u8) -> Option<EntityDirection> {
    match v {
        0 => Some(EntityDirection::North),
        1 => Some(EntityDirection::East),
        2 => Some(EntityDirection::South),
        3 => Some(EntityDirection::West),
        _ => None,
    }
}

/// Encode a cache-bound entity into `[kind, x, y, dir, carries_idx]`.
/// `carries_idx` is `-1` for `None`, else the canonical channel position
/// parsed out of the `"chN"` token.
///
/// Returns `None` if the entity isn't a known belt/UG kind or has a `carries`
/// that isn't a `chN` token — i.e. shouldn't have come out of `extract_solution`.
fn entity_to_tuple(e: &PlacedEntity) -> Option<[i32; 5]> {
    let kind = EntityKind::from_entity(e)? as i32;
    let dir = dir_to_u8(e.direction) as i32;
    let carries_idx = match e.carries.as_deref() {
        None => -1,
        Some(t) => t.strip_prefix("ch").and_then(|n| n.parse::<i32>().ok())?,
    };
    Some([kind, e.x, e.y, dir, carries_idx])
}

/// Decode `[kind, x, y, dir, carries_idx]` back into a `PlacedEntity`. The
/// resulting entity has `segment_id: None` (filled in at lookup replay
/// against the new zone's coords).
fn entity_from_tuple(t: [i32; 5]) -> Option<PlacedEntity> {
    let kind = EntityKind::from_u8(u8::try_from(t[0]).ok()?)?;
    let (name, io) = kind.name_and_io();
    let direction = dir_from_u8(u8::try_from(t[3]).ok()?)?;
    let carries = if t[4] < 0 {
        None
    } else {
        Some(format!("ch{}", t[4]))
    };
    Some(PlacedEntity {
        name: name.to_string(),
        x: t[1],
        y: t[2],
        direction,
        io_type: io.map(str::to_string),
        carries,
        ..Default::default()
    })
}

// ---------------------------------------------------------------------------
// Binary record format (cache file `sat-zones.bin`)
// ---------------------------------------------------------------------------
//
// File = sequence of records, each `u32 LE body_len | body[body_len]`.
// Bodies are self-describing (start with `u8 version`) so future schema
// changes can coexist in the same file. Strings are length-prefixed
// `u16 LE len | utf8 bytes`. Entities are 5 bytes:
// `[kind:u8, x:u8, y:u8, dir:u8, carries_idx:i8]`.
//
// Designed to be parseable from a `&[u8]` with no I/O, so the same loader
// works for native (`std::fs::read`) and WASM (`include_bytes!`).

/// Schema version of records emitted by this build. Bumped on incompatible
/// payload changes; the decoder rejects unknown versions.
const RECORD_VERSION: u8 = 1;

/// Telemetry fields decoded from a record. Only `signature` and the
/// cache-payload subset (entities, channel_items, canon_w/h) are needed for
/// cache hits; the rest is for diag tools (histogram, dumps).
#[derive(Debug, Clone)]
pub struct DecodedRecord {
    pub ts: u64,
    pub signature: String,
    pub source: Option<String>,
    pub canon_w: u32,
    pub canon_h: u32,
    pub variables: u32,
    pub clauses: u32,
    pub solve_time_us: u64,
    pub channel_items: Vec<String>,
    pub entities: Vec<PlacedEntity>,
}

/// Append a length-prefixed `u16` UTF-8 string to `buf`. Strings longer than
/// 65535 bytes are truncated — should never happen for our data (signatures
/// are <200 bytes, item names <30 bytes).
fn write_str(buf: &mut Vec<u8>, s: &str) {
    let bytes = s.as_bytes();
    let len = u16::try_from(bytes.len()).unwrap_or(u16::MAX);
    buf.extend_from_slice(&len.to_le_bytes());
    buf.extend_from_slice(&bytes[..len as usize]);
}

/// Read a length-prefixed `u16` UTF-8 string from `slice`, advancing the
/// cursor. Returns `None` if the slice is too short or the bytes aren't UTF-8.
fn read_str(cursor: &mut &[u8]) -> Option<String> {
    if cursor.len() < 2 {
        return None;
    }
    let len = u16::from_le_bytes([cursor[0], cursor[1]]) as usize;
    *cursor = &cursor[2..];
    if cursor.len() < len {
        return None;
    }
    let s = std::str::from_utf8(&cursor[..len]).ok()?.to_string();
    *cursor = &cursor[len..];
    Some(s)
}

fn read_u8(cursor: &mut &[u8]) -> Option<u8> {
    if cursor.is_empty() { return None; }
    let v = cursor[0];
    *cursor = &cursor[1..];
    Some(v)
}

fn read_u16(cursor: &mut &[u8]) -> Option<u16> {
    if cursor.len() < 2 { return None; }
    let v = u16::from_le_bytes([cursor[0], cursor[1]]);
    *cursor = &cursor[2..];
    Some(v)
}

fn read_u32(cursor: &mut &[u8]) -> Option<u32> {
    if cursor.len() < 4 { return None; }
    let v = u32::from_le_bytes([cursor[0], cursor[1], cursor[2], cursor[3]]);
    *cursor = &cursor[4..];
    Some(v)
}

fn read_u64(cursor: &mut &[u8]) -> Option<u64> {
    if cursor.len() < 8 { return None; }
    let mut arr = [0u8; 8];
    arr.copy_from_slice(&cursor[..8]);
    *cursor = &cursor[8..];
    Some(u64::from_le_bytes(arr))
}

/// Encode a complete record (length prefix + body) into `buf`.
///
/// Layout:
/// ```text
/// u32 LE body_len
///   u8       version (=1)
///   u64 LE   ts
///   u32 LE   variables
///   u32 LE   clauses
///   u64 LE   solve_time_us
///   u8       canon_w     (zone dims always ≤ 255)
///   u8       canon_h
///   u16+str  signature
///   u16+str  source      (zero-length = None)
///   u8       n_channels
///   ×n       u16+str channel_items[i]
///   u16 LE   n_entities
///   ×n       [u8 kind, u8 x, u8 y, u8 dir, i8 carries_idx]
/// ```
pub fn encode_record(
    buf: &mut Vec<u8>,
    ts: u64,
    signature: &str,
    source: Option<&str>,
    canon_w: u32,
    canon_h: u32,
    variables: u32,
    clauses: u32,
    solve_time_us: u64,
    channel_items: &[String],
    entities: &[[i32; 5]],
) {
    let mut body: Vec<u8> = Vec::with_capacity(64 + entities.len() * 5);
    body.push(RECORD_VERSION);
    body.extend_from_slice(&ts.to_le_bytes());
    body.extend_from_slice(&variables.to_le_bytes());
    body.extend_from_slice(&clauses.to_le_bytes());
    body.extend_from_slice(&solve_time_us.to_le_bytes());
    body.push(u8::try_from(canon_w).unwrap_or(u8::MAX));
    body.push(u8::try_from(canon_h).unwrap_or(u8::MAX));
    write_str(&mut body, signature);
    write_str(&mut body, source.unwrap_or(""));
    body.push(u8::try_from(channel_items.len()).unwrap_or(u8::MAX));
    for it in channel_items {
        write_str(&mut body, it);
    }
    let n_ent = u16::try_from(entities.len()).unwrap_or(u16::MAX);
    body.extend_from_slice(&n_ent.to_le_bytes());
    for t in entities.iter().take(n_ent as usize) {
        body.push(u8::try_from(t[0]).unwrap_or(0));
        body.push(u8::try_from(t[1]).unwrap_or(0));
        body.push(u8::try_from(t[2]).unwrap_or(0));
        body.push(u8::try_from(t[3]).unwrap_or(0));
        body.push((t[4].clamp(-128, 127)) as i8 as u8);
    }

    let body_len = u32::try_from(body.len()).unwrap_or(u32::MAX);
    buf.extend_from_slice(&body_len.to_le_bytes());
    buf.extend_from_slice(&body);
}

/// Decode the next record from `bytes`, advancing the slice past it. Returns
/// `None` on malformed input or unknown version.
fn decode_record(bytes: &mut &[u8]) -> Option<DecodedRecord> {
    let body_len = read_u32(bytes)? as usize;
    if bytes.len() < body_len {
        return None;
    }
    let mut body = &bytes[..body_len];
    *bytes = &bytes[body_len..];

    let version = read_u8(&mut body)?;
    if version != RECORD_VERSION {
        return None;
    }
    let ts = read_u64(&mut body)?;
    let variables = read_u32(&mut body)?;
    let clauses = read_u32(&mut body)?;
    let solve_time_us = read_u64(&mut body)?;
    let canon_w = read_u8(&mut body)? as u32;
    let canon_h = read_u8(&mut body)? as u32;
    let signature = read_str(&mut body)?;
    let source_raw = read_str(&mut body)?;
    let source = if source_raw.is_empty() { None } else { Some(source_raw) };

    let n_channels = read_u8(&mut body)? as usize;
    let mut channel_items = Vec::with_capacity(n_channels);
    for _ in 0..n_channels {
        channel_items.push(read_str(&mut body)?);
    }
    let n_entities = read_u16(&mut body)? as usize;
    let mut entities = Vec::with_capacity(n_entities);
    for _ in 0..n_entities {
        if body.len() < 5 { return None; }
        let kind = body[0];
        let x = body[1] as i32;
        let y = body[2] as i32;
        let dir = body[3];
        let carries_idx = body[4] as i8 as i32;
        body = &body[5..];
        let tuple = [kind as i32, x, y, dir as i32, carries_idx];
        if let Some(e) = entity_from_tuple(tuple) {
            entities.push(e);
        }
    }

    Some(DecodedRecord {
        ts, signature, source,
        canon_w, canon_h,
        variables, clauses, solve_time_us,
        channel_items, entities,
    })
}

/// Parse a complete byte slice as a sequence of records. Stops at the first
/// malformed record (skipping the rest of the file). Pure-Rust, no I/O —
/// safe to call from WASM with `include_bytes!()` of a pre-baked cache.
pub fn parse_records(mut bytes: &[u8]) -> Vec<DecodedRecord> {
    let mut out = Vec::new();
    while !bytes.is_empty() {
        match decode_record(&mut bytes) {
            Some(rec) => out.push(rec),
            None => break,
        }
    }
    out
}

/// Format a (edge, offset) port endpoint as e.g. `N2` or `E0`.
fn format_endpoint(edge: u8, offset: u32) -> String {
    let e = match edge {
        0 => 'N',
        1 => 'E',
        2 => 'S',
        3 => 'W',
        _ => '?',
    };
    format!("{}{}", e, offset)
}

/// Compute the canonical orientation-invariant signature for a SAT crossing
/// zone.
///
/// Format: `"{W}x{H}:{channels}|F:{forbidden}|UG:{cap}"`
///
/// - `channels`: per-channel tuples `"{in_endpoints}>{out_endpoints}@{reach}"`,
///   joined by `;`. Each endpoint list is sorted (e.g. `N1+S2>E0@5`), so
///   "channel A enters at N1 and S2, exits at E0, has reach 5".
/// - `forbidden`: sorted list of `"{x},{y}"` interior tiles, joined by `;`.
/// - `cap`: `max_ug_ins` value, or `*` for unlimited.
///
/// Tries all 8 D4 symmetries (4 rotations × 2 reflections), transforms ports
/// AND forbidden tiles together, and returns the lex-smallest rendering.
///
/// Thin wrapper around [`canonicalise`] that throws away the orientation tag.
pub fn canonical_signature(
    zone: &CrossingZone,
    channel_reaches: &[u32],
    max_ug_ins: Option<u32>,
) -> String {
    canonicalise(zone, channel_reaches, max_ug_ins).signature
}

/// Result of canonicalising a crossing zone — the signature plus enough
/// orientation metadata to round-trip a stored SAT solution back into the
/// original (or any same-shape) zone's coordinate frame.
#[derive(Debug, Clone)]
pub struct CanonicalForm {
    /// Lex-min rendering across all 8 D4 transforms — the cache key.
    pub signature: String,
    /// Number of 90° clockwise rotations applied to reach the canonical
    /// orientation. 0..4.
    pub rotation: u8,
    /// Whether a vertical-axis reflection is applied (before rotation) to
    /// reach the canonical orientation.
    pub reflect: bool,
    /// Canonical channel ordering: `channel_order[i]` is the source-zone
    /// `channel_id` whose channel string ended up at position `i` in the
    /// sorted-channel list inside the canonical signature.
    ///
    /// Used to map between item names (which live on `channel_id`s in the
    /// source zone) and canonical channel positions (which the cache stores).
    pub channel_order: Vec<u32>,
}

/// Canonicalise a crossing zone: compute its signature plus the orientation
/// and channel mapping required to translate stored SAT solutions back into
/// this zone's frame.
pub fn canonicalise(
    zone: &CrossingZone,
    channel_reaches: &[u32],
    max_ug_ins: Option<u32>,
) -> CanonicalForm {
    // Base port info: (edge, offset, channel_id, is_input)
    let base_ports: Vec<(u8, u32, u32, bool)> = zone
        .boundaries
        .iter()
        .filter_map(|b| {
            let (edge, offset) =
                edge_and_offset(zone.x, zone.y, zone.width, zone.height, b.x, b.y, b.direction)?;
            let edge_idx = match edge {
                Edge::N => 0,
                Edge::E => 1,
                Edge::S => 2,
                Edge::W => 3,
            };
            Some((edge_idx, offset, b.channel_id, b.is_input))
        })
        .collect();

    // Base forbidden tiles in local zone coords.
    let base_forbidden: Vec<(u32, u32)> = zone
        .forced_empty
        .iter()
        .filter_map(|&(wx, wy)| {
            let lx = wx - zone.x;
            let ly = wy - zone.y;
            if lx < 0 || ly < 0 || lx as u32 >= zone.width || ly as u32 >= zone.height {
                return None;
            }
            Some((lx as u32, ly as u32))
        })
        .collect();

    let cap_str = match max_ug_ins {
        None => "*".to_string(),
        Some(k) => k.to_string(),
    };

    // Track each candidate as (signature, rotation, reflect, channel_order).
    let mut candidates: Vec<(String, u8, bool, Vec<u32>)> = Vec::with_capacity(8);

    for rotation in 0u8..4 {
        for &reflect in &[false, true] {
            let (tw, th) = if rotation.is_multiple_of(2) {
                (zone.width, zone.height)
            } else {
                (zone.height, zone.width)
            };

            // Group transformed ports by channel_id.
            let mut by_channel: std::collections::BTreeMap<u32, (Vec<String>, Vec<String>)> =
                Default::default();
            for &(edge_idx, offset, channel_id, is_input) in &base_ports {
                let (ne, no, _, _) =
                    transform_port(edge_idx, offset, zone.width, zone.height, rotation, reflect);
                let ep = format_endpoint(ne, no);
                let entry = by_channel.entry(channel_id).or_default();
                if is_input {
                    entry.0.push(ep);
                } else {
                    entry.1.push(ep);
                }
            }

            // (channel_id, channel_string) — keep the id alongside so we
            // can read the canonical position → id mapping after sorting.
            let mut channel_pairs: Vec<(u32, String)> = by_channel
                .into_iter()
                .map(|(channel_id, (mut ins, mut outs))| {
                    ins.sort_unstable();
                    outs.sort_unstable();
                    let reach = channel_reaches
                        .get(channel_id as usize)
                        .copied()
                        .unwrap_or(0);
                    (
                        channel_id,
                        format!("{}>{}@{}", ins.join("+"), outs.join("+"), reach),
                    )
                })
                .collect();
            // Sort by string only — the channel_id label itself is not
            // canonical (it's the SAT-encoder's allocation order). Tie-break
            // on channel_id so equal strings produce a deterministic order.
            channel_pairs.sort_by(|a, b| a.1.cmp(&b.1).then_with(|| a.0.cmp(&b.0)));

            let channel_order: Vec<u32> = channel_pairs.iter().map(|(id, _)| *id).collect();
            let channel_strs: Vec<String> =
                channel_pairs.into_iter().map(|(_, s)| s).collect();

            let mut fb: Vec<(u32, u32)> = base_forbidden
                .iter()
                .map(|&(x, y)| transform_tile(x, y, zone.width, zone.height, rotation, reflect))
                .collect();
            fb.sort_unstable();
            let fb_str: Vec<String> = fb.iter().map(|(x, y)| format!("{},{}", x, y)).collect();

            let signature = format!(
                "{}x{}:{}|F:{}|UG:{}",
                tw,
                th,
                channel_strs.join(";"),
                fb_str.join(";"),
                cap_str
            );

            candidates.push((signature, rotation, reflect, channel_order));
        }
    }

    // Pick the canonical: lex-min by signature, tie-break on (rotation, reflect)
    // so repeated calls on the same zone always produce the same orientation.
    candidates.sort_by(|a, b| {
        a.0.cmp(&b.0)
            .then_with(|| a.1.cmp(&b.1))
            .then_with(|| a.2.cmp(&b.2))
    });

    let (signature, rotation, reflect, channel_order) = candidates
        .into_iter()
        .next()
        .unwrap_or_else(|| (String::new(), 0, false, Vec::new()));

    CanonicalForm {
        signature,
        rotation,
        reflect,
        channel_order,
    }
}

/// Flush the buffered records to disk.
///
/// Each record is written in a single `write_all` call against an `O_APPEND`
/// file. Lines are kept short (well under the 4 KiB POSIX `PIPE_BUF`
/// guarantee) so concurrent processes appending to the same file produce
/// interleaved-but-intact lines, never torn ones.
///
/// Silently no-ops on any I/O error — losing telemetry is preferable to
/// failing the calling test or CLI invocation.
///
/// Safe to call any number of times; only the records buffered since the
/// previous call are written.
///
/// No-op in WASM builds (no filesystem). The in-memory buffer is never
/// populated there, so this never has anything to do.
#[cfg(not(target_arch = "wasm32"))]
pub fn flush() {
    let pending: Vec<PendingRecord> = match buffer().lock() {
        Ok(mut buf) => std::mem::take(&mut *buf),
        Err(_) => return,
    };
    if pending.is_empty() {
        return;
    }

    let path = resolve_cache_path();
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    let Ok(mut f) = std::fs::OpenOptions::new()
        .append(true)
        .create(true)
        .open(&path)
    else {
        // Couldn't open — drop the buffer rather than retry-spinning. The
        // records are already lost from the in-memory buffer (we drained
        // it); accept that. A retry path would risk unbounded growth if
        // the disk is permanently unwritable.
        return;
    };

    for record in &pending {
        // O_APPEND + single write_all per record: kernel guarantees the
        // append is atomic for buffers up to PIPE_BUF (4 KiB on Linux).
        // Binary records are typically 100-300 bytes, well under the limit
        // even for the largest zones, so concurrent writers from other
        // processes get interleaved-but-intact records, never torn ones.
        let _ = f.write_all(&record.bytes);
    }
}

/// In WASM builds `flush` is a no-op so callers don't need to cfg-gate.
#[cfg(target_arch = "wasm32")]
pub fn flush() {}

/// Number of records currently buffered, awaiting flush. Useful for sizing
/// diagnostics ("how much will the next flush write?"). Always 0 in WASM.
#[cfg(not(target_arch = "wasm32"))]
pub fn pending_count() -> usize {
    buffer().lock().map(|b| b.len()).unwrap_or(0)
}
#[cfg(target_arch = "wasm32")]
pub fn pending_count() -> usize { 0 }

// ---------------------------------------------------------------------------
// Solution cache — record + lookup
// ---------------------------------------------------------------------------

/// A cached SAT solution stored by canonical signature.
///
/// `entities` are in canonical-frame local coords: x ∈ [0, canon_w), y ∈ [0,
/// canon_h), and each entity's `carries` is either `None` or a channel-token
/// `"ch{N}"` referring to position N in `channel_items`. `segment_id` is
/// stripped (rewritten at replay time using the new zone's coords).
#[derive(Debug, Clone)]
struct CacheEntry {
    entities: Vec<PlacedEntity>,
    /// Items by canonical channel position. `channel_items[i]` is the item
    /// that flowed through canonical-channel-position `i` at record time.
    /// At lookup time we replace each `"ch{i}"` token with the item flowing
    /// through that same canonical position in the new zone.
    channel_items: Vec<String>,
    /// Canonical zone dimensions — needed for the inverse-transform call.
    canon_w: u32,
    canon_h: u32,
}

/// Lazy-loaded read-side cache. First lookup (re)reads the on-disk JSONL,
/// in-session writes append directly so cache hits work for repeats inside
/// the same run too.
static LOOKUP: OnceLock<Mutex<std::collections::HashMap<String, CacheEntry>>> = OnceLock::new();

fn lookup_table() -> &'static Mutex<std::collections::HashMap<String, CacheEntry>> {
    LOOKUP.get_or_init(|| {
        let mut map = std::collections::HashMap::new();
        #[cfg(not(target_arch = "wasm32"))]
        load_existing_jsonl(&mut map);
        #[cfg(target_arch = "wasm32")]
        install_prebaked_into(&mut map, EMBEDDED_CACHE);
        Mutex::new(map)
    })
}

/// Decode a binary cache blob and seed the in-memory lookup map. Pure-Rust,
/// safe to call from WASM (the on-disk loader is gated out there).
///
/// Records that don't decode are silently skipped — robust against truncated
/// or version-mismatched bytes. Newer records (later in the byte slice) win
/// on duplicate signatures.
pub fn install_prebaked(bytes: &[u8]) {
    let tbl = lookup_table();
    if let Ok(mut map) = tbl.lock() {
        install_prebaked_into(&mut map, bytes);
    }
}

fn install_prebaked_into(
    map: &mut std::collections::HashMap<String, CacheEntry>,
    bytes: &[u8],
) {
    for rec in parse_records(bytes) {
        let entry = CacheEntry {
            entities: rec.entities,
            channel_items: rec.channel_items,
            canon_w: rec.canon_w,
            canon_h: rec.canon_h,
        };
        map.insert(rec.signature, entry);
    }
}

/// Populate the lookup map from on-disk caches. Reads `sat-zones.bin`
/// (the canonical format) plus any legacy `sat-zones.jsonl` next to it for
/// backward compat — neither file is required. Binary records win when the
/// same signature appears in both files.
#[cfg(not(target_arch = "wasm32"))]
fn load_existing_jsonl(map: &mut std::collections::HashMap<String, CacheEntry>) {
    // Legacy JSONL first so binary records overwrite any duplicate sigs.
    let legacy = resolve_legacy_jsonl_path();
    if let Ok(contents) = std::fs::read_to_string(&legacy) {
        for line in contents.lines() {
            let Ok(value) = serde_json::from_str::<serde_json::Value>(line) else { continue };
            let entry_opt = if value.get("rv").and_then(|v| v.as_u64()) == Some(1) {
                parse_v1_record(&value)
            } else {
                parse_v0_record(&value)
            };
            if let Some((sig, entry)) = entry_opt {
                map.insert(sig, entry);
            }
        }
    }

    let bin = resolve_cache_path();
    if let Ok(bytes) = std::fs::read(&bin) {
        for rec in parse_records(&bytes) {
            let entry = CacheEntry {
                entities: rec.entities,
                channel_items: rec.channel_items,
                canon_w: rec.canon_w,
                canon_h: rec.canon_h,
            };
            map.insert(rec.signature, entry);
        }
    }
}

/// Parse a v1 (compact JSONL) record. Returns `(signature, entry)` on
/// success. Used only for legacy `.jsonl` reads — new writes go to the
/// binary file.
#[cfg(not(target_arch = "wasm32"))]
fn parse_v1_record(value: &serde_json::Value) -> Option<(String, CacheEntry)> {
    let sig = value["s"].as_str()?.to_string();
    let canon_w = value["cw"].as_u64()? as u32;
    let canon_h = value["ch"].as_u64()? as u32;
    if canon_w == 0 || canon_h == 0 {
        return None;
    }
    let channel_items: Vec<String> =
        serde_json::from_value(value.get("ci")?.clone()).ok()?;
    let tuples: Vec<[i32; 5]> = serde_json::from_value(value.get("e")?.clone()).ok()?;
    let entities: Vec<PlacedEntity> = tuples
        .into_iter()
        .filter_map(entity_from_tuple)
        .collect();
    Some((sig, CacheEntry { entities, channel_items, canon_w, canon_h }))
}

/// Parse a v0 (legacy verbose) record. Returns `(signature, entry)` on success.
#[cfg(not(target_arch = "wasm32"))]
fn parse_v0_record(value: &serde_json::Value) -> Option<(String, CacheEntry)> {
    let sig = value["signature"].as_str()?.to_string();
    let entities: Vec<PlacedEntity> = serde_json::from_value(value.get("entities")?.clone()).ok()?;
    let channel_items: Vec<String> =
        serde_json::from_value(value.get("channel_items")?.clone()).ok()?;
    let canon_w = value["canon_w"].as_u64()? as u32;
    let canon_h = value["canon_h"].as_u64()? as u32;
    if canon_w == 0 || canon_h == 0 {
        return None;
    }
    Some((sig, CacheEntry { entities, channel_items, canon_w, canon_h }))
}

/// Whether to consult the cache on lookup. Defaults to enabled —
/// `record_zone_with_solution` always records regardless. Set
/// `FUCKTORIO_USE_ZONE_CACHE=0` to disable (e.g. when investigating a
/// suspected stale-cache regression). WASM builds always have it on
/// (no env vars).
fn cache_enabled() -> bool {
    #[cfg(target_arch = "wasm32")]
    { true }
    #[cfg(not(target_arch = "wasm32"))]
    {
        !matches!(
            std::env::var("FUCKTORIO_USE_ZONE_CACHE").as_deref(),
            Ok("0") | Ok("false") | Ok("False") | Ok("FALSE")
        )
    }
}

/// Build a `channel_id → item` map from boundaries. Boundaries sharing a
/// channel_id always carry the same item, so we just take the first.
fn channel_items_by_id(zone: &CrossingZone) -> std::collections::HashMap<u32, String> {
    let mut map: std::collections::HashMap<u32, String> = Default::default();
    for b in &zone.boundaries {
        map.entry(b.channel_id).or_insert_with(|| b.item.clone());
    }
    map
}

/// Build the canonical-position-indexed item list using a `CanonicalForm`.
fn canonical_channel_items(zone: &CrossingZone, form: &CanonicalForm) -> Vec<String> {
    let by_id = channel_items_by_id(zone);
    form.channel_order
        .iter()
        .map(|id| by_id.get(id).cloned().unwrap_or_default())
        .collect()
}

/// Rewrite an entity's `carries` from a real item to a canonical channel
/// token. Returns the entity with `carries` replaced by `Some("chN")` if the
/// item is found in `channel_items`, or unchanged otherwise.
fn entity_carries_to_token(mut e: PlacedEntity, channel_items: &[String]) -> PlacedEntity {
    if let Some(item) = e.carries.as_deref() {
        if let Some(pos) = channel_items.iter().position(|i| i == item) {
            e.carries = Some(format!("ch{pos}"));
        }
    }
    e
}

/// Reverse of `entity_carries_to_token`: replace `"chN"` with the actual
/// item at that canonical position.
fn entity_carries_from_token(mut e: PlacedEntity, channel_items: &[String]) -> PlacedEntity {
    if let Some(token) = e.carries.as_deref() {
        if let Some(idx_str) = token.strip_prefix("ch") {
            if let Ok(idx) = idx_str.parse::<usize>() {
                if let Some(item) = channel_items.get(idx) {
                    e.carries = Some(item.clone());
                }
            }
        }
    }
    e
}

/// Record a SAT-solved zone with its solution entities for future lookup.
/// Extends [`record_zone`] by also storing the entities (rewritten to
/// canonical-frame local coords with channel-token `carries`).
///
/// `entities` should be the post-cost-descent SAT output, in absolute world
/// coords (as returned by `solve_crossing_zone_per_channel`). We strip the
/// world-coord origin and apply the canonical transform before storing.
pub fn record_zone_with_solution(
    zone: &CrossingZone,
    channel_reaches: &[u32],
    max_ug_ins: Option<u32>,
    stats: ZoneStats,
    entities: &[PlacedEntity],
    source: Option<&str>,
) {
    let form = canonicalise(zone, channel_reaches, max_ug_ins);
    let channel_items = canonical_channel_items(zone, &form);

    // Convert entities: absolute → zone-local → canonical-frame.
    let (canon_w, canon_h) = if form.rotation.is_multiple_of(2) {
        (zone.width, zone.height)
    } else {
        (zone.height, zone.width)
    };

    let canonical_entities: Vec<PlacedEntity> = entities
        .iter()
        .filter_map(|e| {
            let mut local = e.clone();
            local.x = e.x - zone.x;
            local.y = e.y - zone.y;
            // Skip entities that escaped the bbox — shouldn't happen but be
            // defensive (we'd produce out-of-bounds coords on transform).
            if local.x < 0
                || local.y < 0
                || (local.x as u32) >= zone.width
                || (local.y as u32) >= zone.height
            {
                return None;
            }
            let transformed = transform_entity(&local, zone.width, zone.height, form.rotation, form.reflect);
            // Strip segment_id — it's per-zone-instance, regenerated at lookup.
            let mut e = transformed;
            e.segment_id = None;
            Some(entity_carries_to_token(e, &channel_items))
        })
        .collect();

    // Update in-memory cache so same-session repeats hit.
    if let Ok(mut tbl) = lookup_table().lock() {
        tbl.insert(
            form.signature.clone(),
            CacheEntry {
                entities: canonical_entities.clone(),
                channel_items: channel_items.clone(),
                canon_w,
                canon_h,
            },
        );
    }

    // Encode the binary record into the buffer.
    let thread_src = ZONE_SOURCE.with(|s| s.borrow().clone());
    let effective_source: Option<String> = thread_src
        .or_else(|| source.map(|s| s.to_string()))
        .or_else(|| std::env::var("FUCKTORIO_ZONE_SOURCE").ok());

    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    // Pack entities as [kind, x, y, dir, carries_idx] tuples. Anything that
    // doesn't encode (unknown name, broken carries token) is dropped — these
    // shouldn't happen for SAT-produced entities.
    let entity_tuples: Vec<[i32; 5]> = canonical_entities
        .iter()
        .filter_map(entity_to_tuple)
        .collect();

    // WASM has nowhere to flush to, so skip the encode + buffer entirely.
    // The in-memory cache update above already gives us same-session reuse.
    #[cfg(not(target_arch = "wasm32"))]
    {
        let mut bytes: Vec<u8> = Vec::with_capacity(64 + entity_tuples.len() * 5);
        encode_record(
            &mut bytes,
            ts,
            &form.signature,
            effective_source.as_deref(),
            canon_w,
            canon_h,
            stats.variables,
            stats.clauses,
            stats.solve_time_us,
            &channel_items,
            &entity_tuples,
        );
        if let Ok(mut buf) = buffer().lock() {
            buf.push(PendingRecord { bytes });
        }
    }
    #[cfg(target_arch = "wasm32")]
    {
        let _ = (ts, effective_source, entity_tuples, &stats);  // silence unused
    }
}

/// Look up a previously-cached SAT solution for `zone`. Returns `Some` of a
/// fresh `Vec<PlacedEntity>` in absolute world coords matching what
/// `solve_crossing_zone_per_channel` would have returned, or `None` on miss
/// or if the cache is disabled (env-gated).
///
/// The returned entities have `segment_id` set to `"crossing:{x}:{y}"` to
/// mirror the SAT path's tagging.
pub fn lookup_zone(
    zone: &CrossingZone,
    channel_reaches: &[u32],
    max_ug_ins: Option<u32>,
) -> Option<Vec<PlacedEntity>> {
    if !cache_enabled() {
        return None;
    }

    let form = canonicalise(zone, channel_reaches, max_ug_ins);
    let entry = {
        let tbl = lookup_table().lock().ok()?;
        tbl.get(&form.signature).cloned()?
    };

    let new_channel_items = canonical_channel_items(zone, &form);

    // Channel-count mismatch would mean either a hash collision or a stale
    // entry from a different encoder; bail rather than return wrong items.
    if new_channel_items.len() != entry.channel_items.len() {
        return None;
    }

    // Inverse-transform entities: canonical-frame → zone-local → absolute.
    let segment_id = format!("crossing:{}:{}", zone.x, zone.y);
    let entities: Vec<PlacedEntity> = entry
        .entities
        .into_iter()
        .map(|e| {
            let local = transform_entity_inverse(&e, entry.canon_w, entry.canon_h, form.rotation, form.reflect);
            let mut out = entity_carries_from_token(local, &new_channel_items);
            out.x += zone.x;
            out.y += zone.y;
            out.segment_id = Some(segment_id.clone());
            out
        })
        .collect();

    Some(entities)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::EntityDirection;
    use crate::sat::ZoneBoundary;

    fn boundary(x: i32, y: i32, dir: EntityDirection, channel_id: u32, is_input: bool) -> ZoneBoundary {
        ZoneBoundary {
            x,
            y,
            direction: dir,
            item: format!("ch{}", channel_id),
            is_input,
            interior: false,
            belt_tier: None,
            channel_id,
        }
    }

    #[test]
    fn parallel_vs_crossed_have_distinct_signatures() {
        // 3x3 zone at (0,0). Two channels.
        // Parallel: ch0 N1->S1, ch1 W1->E1
        let parallel = CrossingZone {
            x: 0, y: 0, width: 3, height: 3,
            boundaries: vec![
                boundary(1, 0, EntityDirection::South, 0, true),  // N1 in
                boundary(1, 2, EntityDirection::South, 0, false), // S1 out
                boundary(0, 1, EntityDirection::East, 1, true),   // W1 in
                boundary(2, 1, EntityDirection::East, 1, false),  // E1 out
            ],
            forced_empty: vec![],
        };
        // Crossed: ch0 N1->E1, ch1 W1->S1
        let crossed = CrossingZone {
            x: 0, y: 0, width: 3, height: 3,
            boundaries: vec![
                boundary(1, 0, EntityDirection::South, 0, true),  // N1 in
                boundary(2, 1, EntityDirection::East, 0, false),  // E1 out
                boundary(0, 1, EntityDirection::East, 1, true),   // W1 in
                boundary(1, 2, EntityDirection::South, 1, false), // S1 out
            ],
            forced_empty: vec![],
        };
        let reaches = [5, 5];
        let sp = canonical_signature(&parallel, &reaches, None);
        let sc = canonical_signature(&crossed, &reaches, None);
        assert_ne!(sp, sc, "parallel and crossed must have different signatures");
    }

    #[test]
    fn rotation_invariant() {
        // 3x3 with one channel N1->S1.
        let z1 = CrossingZone {
            x: 0, y: 0, width: 3, height: 3,
            boundaries: vec![
                boundary(1, 0, EntityDirection::South, 0, true),
                boundary(1, 2, EntityDirection::South, 0, false),
            ],
            forced_empty: vec![],
        };
        // Same shape rotated 90° CW: W1->E1.
        let z2 = CrossingZone {
            x: 0, y: 0, width: 3, height: 3,
            boundaries: vec![
                boundary(0, 1, EntityDirection::East, 0, true),
                boundary(2, 1, EntityDirection::East, 0, false),
            ],
            forced_empty: vec![],
        };
        let reaches = [5];
        assert_eq!(
            canonical_signature(&z1, &reaches, None),
            canonical_signature(&z2, &reaches, None)
        );
    }

    #[test]
    fn forbidden_tiles_co_transform() {
        // Same connectivity but different forbidden tile placements: should
        // produce different signatures.
        let mk = |fb: Vec<(i32, i32)>| CrossingZone {
            x: 0, y: 0, width: 3, height: 3,
            boundaries: vec![
                boundary(1, 0, EntityDirection::South, 0, true),
                boundary(1, 2, EntityDirection::South, 0, false),
            ],
            forced_empty: fb,
        };
        let za = mk(vec![(0, 1)]); // forbidden on left
        let zb = mk(vec![(2, 1)]); // forbidden on right — same under reflect though
        // These two are reflection-equivalent, so should match.
        assert_eq!(
            canonical_signature(&za, &[5], None),
            canonical_signature(&zb, &[5], None)
        );

        // But a forbidden tile at the center should be different from one on
        // an edge.
        let zc = mk(vec![(1, 1)]);
        assert_ne!(
            canonical_signature(&za, &[5], None),
            canonical_signature(&zc, &[5], None)
        );
    }

    #[test]
    fn ug_cap_in_key() {
        let z = CrossingZone {
            x: 0, y: 0, width: 3, height: 3,
            boundaries: vec![
                boundary(1, 0, EntityDirection::South, 0, true),
                boundary(1, 2, EntityDirection::South, 0, false),
            ],
            forced_empty: vec![],
        };
        assert_ne!(
            canonical_signature(&z, &[5], None),
            canonical_signature(&z, &[5], Some(0))
        );
    }

    fn ent(name: &str, x: i32, y: i32, dir: EntityDirection) -> PlacedEntity {
        PlacedEntity {
            name: name.to_string(),
            x,
            y,
            direction: dir,
            ..Default::default()
        }
    }

    /// Round-trip: forward then inverse with the same (rot, refl) is identity
    /// for every D4 element. Tests every (rot ∈ 0..4) × (refl ∈ {false, true}).
    #[test]
    fn transform_roundtrip_identity() {
        let original = [
            ent("transport-belt", 0, 0, EntityDirection::East),
            ent("transport-belt", 2, 1, EntityDirection::North),
            ent("fast-underground-belt", 4, 2, EntityDirection::South),
            ent("transport-belt", 1, 3, EntityDirection::West),
        ];
        let (w, h) = (5u32, 4u32);

        for rot in 0u8..4 {
            for &refl in &[false, true] {
                // Forward: original → canonical frame.
                let (tw, th) = if rot.is_multiple_of(2) { (w, h) } else { (h, w) };
                let canonical: Vec<PlacedEntity> = original
                    .iter()
                    .map(|e| transform_entity(e, w, h, rot, refl))
                    .collect();

                // Sanity: every canonical entity sits inside the post-transform bbox.
                for e in &canonical {
                    assert!(e.x >= 0 && (e.x as u32) < tw, "rot={rot} refl={refl}: x={} out of bounds (tw={})", e.x, tw);
                    assert!(e.y >= 0 && (e.y as u32) < th, "rot={rot} refl={refl}: y={} out of bounds (th={})", e.y, th);
                }

                // Inverse: canonical → original frame.
                let recovered: Vec<PlacedEntity> = canonical
                    .iter()
                    .map(|e| transform_entity_inverse(e, tw, th, rot, refl))
                    .collect();

                for (orig, rec) in original.iter().zip(recovered.iter()) {
                    assert_eq!(
                        (orig.x, orig.y, orig.direction),
                        (rec.x, rec.y, rec.direction),
                        "rot={rot} refl={refl} roundtrip mismatch on {} at ({},{}) dir={:?}",
                        orig.name, orig.x, orig.y, orig.direction
                    );
                }
            }
        }
    }

    /// Specific orientation: 90°CW rotation should map (1, 0) North in a
    /// 3×3 zone to (2, 1) East in the rotated 3×3 zone.
    #[test]
    fn transform_90cw_specific() {
        let e = ent("transport-belt", 1, 0, EntityDirection::North);
        let t = transform_entity(&e, 3, 3, 1, false);
        assert_eq!((t.x, t.y), (2, 1), "position mapping wrong");
        assert_eq!(t.direction, EntityDirection::East, "direction mapping wrong");
    }

    /// Every belt/UG kind round-trips through the compact tuple encoding.
    #[test]
    fn entity_tuple_roundtrip_all_kinds() {
        let cases = [
            ("transport-belt", None, EntityDirection::North),
            ("fast-transport-belt", None, EntityDirection::East),
            ("express-transport-belt", None, EntityDirection::South),
            ("underground-belt", Some("input"), EntityDirection::West),
            ("underground-belt", Some("output"), EntityDirection::North),
            ("fast-underground-belt", Some("input"), EntityDirection::East),
            ("fast-underground-belt", Some("output"), EntityDirection::South),
            ("express-underground-belt", Some("input"), EntityDirection::West),
            ("express-underground-belt", Some("output"), EntityDirection::North),
        ];
        for (name, io, dir) in cases {
            let e = PlacedEntity {
                name: name.to_string(),
                x: 3,
                y: 7,
                direction: dir,
                io_type: io.map(str::to_string),
                carries: Some("ch2".to_string()),
                ..Default::default()
            };
            let t = entity_to_tuple(&e).expect("encode");
            let r = entity_from_tuple(t).expect("decode");
            assert_eq!(r.name, e.name, "name mismatch for {name}");
            assert_eq!(r.x, e.x);
            assert_eq!(r.y, e.y);
            assert_eq!(r.direction, e.direction);
            assert_eq!(r.io_type, e.io_type, "io_type mismatch for {name}");
            assert_eq!(r.carries, e.carries);
        }
    }

    /// Carries `None` round-trips as `-1`.
    #[test]
    fn entity_tuple_carries_none() {
        let e = PlacedEntity {
            name: "transport-belt".to_string(),
            x: 0, y: 0,
            direction: EntityDirection::North,
            carries: None,
            ..Default::default()
        };
        let t = entity_to_tuple(&e).unwrap();
        assert_eq!(t[4], -1);
        let r = entity_from_tuple(t).unwrap();
        assert_eq!(r.carries, None);
    }

    #[test]
    fn binary_record_roundtrip() {
        let entities: Vec<[i32; 5]> = vec![
            [1, 10, 2, 3, 0],   // fast-belt at (10,2) west, ch0
            [6, 8, 3, 2, 1],    // fast-UG-out at (8,3) south, ch1
            [0, 0, 0, 0, -1],   // yellow belt at (0,0) north, no carries
        ];
        let channel_items = vec!["copper-plate".to_string(), "iron-plate".to_string()];

        let mut buf = Vec::new();
        encode_record(
            &mut buf,
            1234567890,
            "11x4:E1+E2>N10+N3@6;N2+N9>S0+S1@6|F:|UG:2",
            Some("test_source"),
            11, 4,
            616, 19428, 3152,
            &channel_items,
            &entities,
        );

        // Append a second record so we test multi-record parsing too.
        encode_record(
            &mut buf,
            1234567891,
            "1x2:N1>N1@6|F:|UG:0",
            None,
            1, 2,
            22, 116, 47,
            &["iron-ore".to_string()],
            &[[1, 0, 1, 0, 0], [1, 0, 0, 0, 0]],
        );

        let recs = parse_records(&buf);
        assert_eq!(recs.len(), 2, "should decode two records");

        assert_eq!(recs[0].ts, 1234567890);
        assert_eq!(recs[0].signature, "11x4:E1+E2>N10+N3@6;N2+N9>S0+S1@6|F:|UG:2");
        assert_eq!(recs[0].source.as_deref(), Some("test_source"));
        assert_eq!((recs[0].canon_w, recs[0].canon_h), (11, 4));
        assert_eq!((recs[0].variables, recs[0].clauses, recs[0].solve_time_us), (616, 19428, 3152));
        assert_eq!(recs[0].channel_items, vec!["copper-plate", "iron-plate"]);
        assert_eq!(recs[0].entities.len(), 3);
        assert_eq!(recs[0].entities[0].name, "fast-transport-belt");
        assert_eq!(recs[0].entities[0].carries.as_deref(), Some("ch0"));
        assert_eq!(recs[0].entities[1].name, "fast-underground-belt");
        assert_eq!(recs[0].entities[1].io_type.as_deref(), Some("output"));
        assert_eq!(recs[0].entities[2].carries, None);

        assert_eq!(recs[1].source, None);
        assert_eq!(recs[1].channel_items, vec!["iron-ore"]);
        assert_eq!(recs[1].entities.len(), 2);
    }

    /// Truncated input should stop cleanly, returning whatever decoded fully.
    #[test]
    fn binary_truncated_input_safe() {
        let mut buf = Vec::new();
        encode_record(&mut buf, 1, "1x2:N0>N0@6|F:|UG:0", None, 1, 2, 0, 0, 0, &[], &[[1, 0, 0, 0, -1]]);
        // Truncate mid-record.
        buf.truncate(buf.len() - 5);
        let recs = parse_records(&buf);
        assert_eq!(recs.len(), 0, "truncated records should be skipped");
    }
}
